package entity

import "errors"

var (
	ErrUserNotFound                 = errors.New("user not found")
	ErrUserAlreadyExists            = errors.New("user already exists")
	ErrInvalidCredentials           = errors.New("invalid credentials")
	ErrLocalAuthDisabled            = errors.New("local authentication is disabled")
	ErrLanguageNotFound             = errors.New("language not found")
	ErrLanguageExists               = errors.New("language code already exists")
	ErrInvalidLanguage              = errors.New("invalid language")
	ErrLevelNotFound                = errors.New("level not found")
	ErrLevelExists                  = errors.New("level already exists for language")
	ErrLevelReferenced              = errors.New("level is referenced by videos")
	ErrInvalidLevel                 = errors.New("invalid level")
	ErrInvalidReference             = errors.New("invalid reference")
	ErrTopicNotFound                = errors.New("topic not found")
	ErrTopicExists                  = errors.New("topic slug already exists")
	ErrTopicReferenced              = errors.New("topic is referenced by videos")
	ErrInvalidTopic                 = errors.New("invalid topic")
	ErrChannelNotFound              = errors.New("channel not found")
	ErrChannelExists                = errors.New("YouTube channel already exists")
	ErrChannelReferenced            = errors.New("channel is referenced by videos")
	ErrInvalidChannel               = errors.New("invalid channel")
	ErrInvalidUserFilter            = errors.New("invalid user filter")
	ErrInvalidUserRole              = errors.New("invalid user role")
	ErrAdminSelfMutation            = errors.New("admin cannot change own status or role")
	ErrVideoNotFound                = errors.New("video not found")
	ErrVideoExists                  = errors.New("YouTube video already exists")
	ErrInvalidVideo                 = errors.New("invalid video")
	ErrTargetLanguageRequired       = errors.New("target language is required")
	ErrNativeLanguageRequired       = errors.New("native language is required")
	ErrInvalidVideoTransition       = errors.New("invalid video status transition")
	ErrConcurrentVideoUpdate        = errors.New("video was updated concurrently")
	ErrCaptionNotFound              = errors.New("caption not found")
	ErrCaptionExists                = errors.New("caption sentence order already exists")
	ErrInvalidCaption               = errors.New("invalid caption")
	ErrInvalidSRT                   = errors.New("invalid srt file")
	ErrCaptionTranslationCount      = errors.New("caption translation count does not match original")
	ErrYouTubeProviderFailed        = errors.New("YouTube provider failed")
	ErrAudioDownloadFailed          = errors.New("YouTube audio download failed")
	ErrTranscriptionFailed          = errors.New("audio transcription provider failed")
	ErrInvalidTranscription         = errors.New("audio transcription response is invalid")
	ErrCaptionTranslationEmpty      = errors.New("video has no captions to translate")
	ErrTranslationUnavailable       = errors.New("caption translation is unavailable")
	ErrTranslationFailed            = errors.New("caption translation provider failed")
	ErrInvalidTranslation           = errors.New("caption translation response is invalid")
	ErrTranslationRateLimited       = errors.New("caption translation rate limit reached")
	ErrDictionaryNotFound           = errors.New("dictionary entry not found")
	ErrInvalidVocabulary            = errors.New("invalid vocabulary")
	ErrInvalidVocabularyTranslation = errors.New("vocabulary translation response is invalid")
	ErrVocabularySetNotFound        = errors.New("vocabulary set not found")
	ErrInvalidVocabularySet         = errors.New("invalid vocabulary set")
	ErrUserVocabularyNotFound       = errors.New("user vocabulary not found")
	ErrUserVocabularyExists         = errors.New("vocabulary already saved in this set")
)
