// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source internal/repo/contracts.go -destination internal/usecase/mocks_repo_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByFirebaseUID mocks base method.
func (m *MockUserRepo) GetByFirebaseUID(ctx context.Context, firebaseUID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFirebaseUID", ctx, firebaseUID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFirebaseUID indicates an expected call of GetByFirebaseUID.
func (mr *MockUserRepoMockRecorder) GetByFirebaseUID(ctx, firebaseUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFirebaseUID", reflect.TypeOf((*MockUserRepo)(nil).GetByFirebaseUID), ctx, firebaseUID)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// MockLanguageRepo is a mock of LanguageRepo interface.
type MockLanguageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageRepoMockRecorder
	isgomock struct{}
}

// MockLanguageRepoMockRecorder is the mock recorder for MockLanguageRepo.
type MockLanguageRepoMockRecorder struct {
	mock *MockLanguageRepo
}

// NewMockLanguageRepo creates a new mock instance.
func NewMockLanguageRepo(ctrl *gomock.Controller) *MockLanguageRepo {
	mock := &MockLanguageRepo{ctrl: ctrl}
	mock.recorder = &MockLanguageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguageRepo) EXPECT() *MockLanguageRepoMockRecorder {
	return m.recorder
}

// CreateLanguage mocks base method.
func (m *MockLanguageRepo) CreateLanguage(ctx context.Context, language *entity.Language) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLanguage", ctx, language)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLanguage indicates an expected call of CreateLanguage.
func (mr *MockLanguageRepoMockRecorder) CreateLanguage(ctx, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLanguage", reflect.TypeOf((*MockLanguageRepo)(nil).CreateLanguage), ctx, language)
}

// ListLanguages mocks base method.
func (m *MockLanguageRepo) ListLanguages(ctx context.Context) ([]entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx)
	ret0, _ := ret[0].([]entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockLanguageRepoMockRecorder) ListLanguages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockLanguageRepo)(nil).ListLanguages), ctx)
}

// UpdateLanguage mocks base method.
func (m *MockLanguageRepo) UpdateLanguage(ctx context.Context, language *entity.Language) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLanguage", ctx, language)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLanguage indicates an expected call of UpdateLanguage.
func (mr *MockLanguageRepoMockRecorder) UpdateLanguage(ctx, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLanguage", reflect.TypeOf((*MockLanguageRepo)(nil).UpdateLanguage), ctx, language)
}

// MockLevelRepo is a mock of LevelRepo interface.
type MockLevelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLevelRepoMockRecorder
	isgomock struct{}
}

// MockLevelRepoMockRecorder is the mock recorder for MockLevelRepo.
type MockLevelRepoMockRecorder struct {
	mock *MockLevelRepo
}

// NewMockLevelRepo creates a new mock instance.
func NewMockLevelRepo(ctrl *gomock.Controller) *MockLevelRepo {
	mock := &MockLevelRepo{ctrl: ctrl}
	mock.recorder = &MockLevelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLevelRepo) EXPECT() *MockLevelRepoMockRecorder {
	return m.recorder
}

// CreateLevel mocks base method.
func (m *MockLevelRepo) CreateLevel(ctx context.Context, level *entity.Level) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLevel", ctx, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLevel indicates an expected call of CreateLevel.
func (mr *MockLevelRepoMockRecorder) CreateLevel(ctx, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLevel", reflect.TypeOf((*MockLevelRepo)(nil).CreateLevel), ctx, level)
}

// DeleteLevel mocks base method.
func (m *MockLevelRepo) DeleteLevel(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLevel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLevel indicates an expected call of DeleteLevel.
func (mr *MockLevelRepoMockRecorder) DeleteLevel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLevel", reflect.TypeOf((*MockLevelRepo)(nil).DeleteLevel), ctx, id)
}

// ListLevels mocks base method.
func (m *MockLevelRepo) ListLevels(ctx context.Context, languageID *int) ([]entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLevels", ctx, languageID)
	ret0, _ := ret[0].([]entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLevels indicates an expected call of ListLevels.
func (mr *MockLevelRepoMockRecorder) ListLevels(ctx, languageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLevels", reflect.TypeOf((*MockLevelRepo)(nil).ListLevels), ctx, languageID)
}

// UpdateLevel mocks base method.
func (m *MockLevelRepo) UpdateLevel(ctx context.Context, level *entity.Level) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLevel", ctx, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLevel indicates an expected call of UpdateLevel.
func (mr *MockLevelRepoMockRecorder) UpdateLevel(ctx, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLevel", reflect.TypeOf((*MockLevelRepo)(nil).UpdateLevel), ctx, level)
}

// MockTopicRepo is a mock of TopicRepo interface.
type MockTopicRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTopicRepoMockRecorder
	isgomock struct{}
}

// MockTopicRepoMockRecorder is the mock recorder for MockTopicRepo.
type MockTopicRepoMockRecorder struct {
	mock *MockTopicRepo
}

// NewMockTopicRepo creates a new mock instance.
func NewMockTopicRepo(ctrl *gomock.Controller) *MockTopicRepo {
	mock := &MockTopicRepo{ctrl: ctrl}
	mock.recorder = &MockTopicRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicRepo) EXPECT() *MockTopicRepoMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method.
func (m *MockTopicRepo) CreateTopic(ctx context.Context, topic *entity.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockTopicRepoMockRecorder) CreateTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockTopicRepo)(nil).CreateTopic), ctx, topic)
}

// DeleteTopic mocks base method.
func (m *MockTopicRepo) DeleteTopic(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockTopicRepoMockRecorder) DeleteTopic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockTopicRepo)(nil).DeleteTopic), ctx, id)
}

// ListTopics mocks base method.
func (m *MockTopicRepo) ListTopics(ctx context.Context) ([]entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx)
	ret0, _ := ret[0].([]entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockTopicRepoMockRecorder) ListTopics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockTopicRepo)(nil).ListTopics), ctx)
}

// SetTopicActive mocks base method.
func (m *MockTopicRepo) SetTopicActive(ctx context.Context, id int, isActive bool) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTopicActive", ctx, id, isActive)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTopicActive indicates an expected call of SetTopicActive.
func (mr *MockTopicRepoMockRecorder) SetTopicActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopicActive", reflect.TypeOf((*MockTopicRepo)(nil).SetTopicActive), ctx, id, isActive)
}

// UpdateTopic mocks base method.
func (m *MockTopicRepo) UpdateTopic(ctx context.Context, topic *entity.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTopic", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTopic indicates an expected call of UpdateTopic.
func (mr *MockTopicRepoMockRecorder) UpdateTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTopic", reflect.TypeOf((*MockTopicRepo)(nil).UpdateTopic), ctx, topic)
}
