// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=../usecase/mocks_repo_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/evrone/go-clean-template/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// CompleteDictation mocks base method.
func (m *MockUserRepo) CompleteDictation(ctx context.Context, userID string, videoID, captionID int64) (entity.DictationProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteDictation", ctx, userID, videoID, captionID)
	ret0, _ := ret[0].(entity.DictationProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteDictation indicates an expected call of CompleteDictation.
func (mr *MockUserRepoMockRecorder) CompleteDictation(ctx, userID, videoID, captionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteDictation", reflect.TypeOf((*MockUserRepo)(nil).CompleteDictation), ctx, userID, videoID, captionID)
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByFirebaseUID mocks base method.
func (m *MockUserRepo) GetByFirebaseUID(ctx context.Context, firebaseUID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFirebaseUID", ctx, firebaseUID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFirebaseUID indicates an expected call of GetByFirebaseUID.
func (mr *MockUserRepoMockRecorder) GetByFirebaseUID(ctx, firebaseUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFirebaseUID", reflect.TypeOf((*MockUserRepo)(nil).GetByFirebaseUID), ctx, firebaseUID)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// GetVideoState mocks base method.
func (m *MockUserRepo) GetVideoState(ctx context.Context, userID string, videoID int64) (entity.VideoState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoState", ctx, userID, videoID)
	ret0, _ := ret[0].(entity.VideoState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoState indicates an expected call of GetVideoState.
func (mr *MockUserRepoMockRecorder) GetVideoState(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoState", reflect.TypeOf((*MockUserRepo)(nil).GetVideoState), ctx, userID, videoID)
}

// GetWatchHistory mocks base method.
func (m *MockUserRepo) GetWatchHistory(ctx context.Context, userID string, videoID int64) (entity.UserVideo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchHistory", ctx, userID, videoID)
	ret0, _ := ret[0].(entity.UserVideo)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWatchHistory indicates an expected call of GetWatchHistory.
func (mr *MockUserRepoMockRecorder) GetWatchHistory(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchHistory", reflect.TypeOf((*MockUserRepo)(nil).GetWatchHistory), ctx, userID, videoID)
}

// ListCompletedDictations mocks base method.
func (m *MockUserRepo) ListCompletedDictations(ctx context.Context, userID string, videoID int64) (entity.DictationProgressList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompletedDictations", ctx, userID, videoID)
	ret0, _ := ret[0].(entity.DictationProgressList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompletedDictations indicates an expected call of ListCompletedDictations.
func (mr *MockUserRepoMockRecorder) ListCompletedDictations(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompletedDictations", reflect.TypeOf((*MockUserRepo)(nil).ListCompletedDictations), ctx, userID, videoID)
}

// ListWatchHistory mocks base method.
func (m *MockUserRepo) ListWatchHistory(ctx context.Context, userID string, limit, offset int) (entity.UserVideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWatchHistory", ctx, userID, limit, offset)
	ret0, _ := ret[0].(entity.UserVideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWatchHistory indicates an expected call of ListWatchHistory.
func (mr *MockUserRepoMockRecorder) ListWatchHistory(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWatchHistory", reflect.TypeOf((*MockUserRepo)(nil).ListWatchHistory), ctx, userID, limit, offset)
}

// ListWatchLater mocks base method.
func (m *MockUserRepo) ListWatchLater(ctx context.Context, userID string, limit, offset int) (entity.UserVideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWatchLater", ctx, userID, limit, offset)
	ret0, _ := ret[0].(entity.UserVideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWatchLater indicates an expected call of ListWatchLater.
func (mr *MockUserRepoMockRecorder) ListWatchLater(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWatchLater", reflect.TypeOf((*MockUserRepo)(nil).ListWatchLater), ctx, userID, limit, offset)
}

// RemoveWatchHistory mocks base method.
func (m *MockUserRepo) RemoveWatchHistory(ctx context.Context, userID string, videoID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWatchHistory", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWatchHistory indicates an expected call of RemoveWatchHistory.
func (mr *MockUserRepoMockRecorder) RemoveWatchHistory(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWatchHistory", reflect.TypeOf((*MockUserRepo)(nil).RemoveWatchHistory), ctx, userID, videoID)
}

// RemoveWatchLater mocks base method.
func (m *MockUserRepo) RemoveWatchLater(ctx context.Context, userID string, videoID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWatchLater", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWatchLater indicates an expected call of RemoveWatchLater.
func (mr *MockUserRepoMockRecorder) RemoveWatchLater(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWatchLater", reflect.TypeOf((*MockUserRepo)(nil).RemoveWatchLater), ctx, userID, videoID)
}

// SaveWatchLater mocks base method.
func (m *MockUserRepo) SaveWatchLater(ctx context.Context, userID string, videoID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWatchLater", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWatchLater indicates an expected call of SaveWatchLater.
func (mr *MockUserRepoMockRecorder) SaveWatchLater(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWatchLater", reflect.TypeOf((*MockUserRepo)(nil).SaveWatchLater), ctx, userID, videoID)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// UpdateFirebaseProfile mocks base method.
func (m *MockUserRepo) UpdateFirebaseProfile(ctx context.Context, id, username, avatarURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFirebaseProfile", ctx, id, username, avatarURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFirebaseProfile indicates an expected call of UpdateFirebaseProfile.
func (mr *MockUserRepoMockRecorder) UpdateFirebaseProfile(ctx, id, username, avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFirebaseProfile", reflect.TypeOf((*MockUserRepo)(nil).UpdateFirebaseProfile), ctx, id, username, avatarURL)
}

// UpdateLanguages mocks base method.
func (m *MockUserRepo) UpdateLanguages(ctx context.Context, id string, nativeLanguageID, targetLanguageID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLanguages", ctx, id, nativeLanguageID, targetLanguageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLanguages indicates an expected call of UpdateLanguages.
func (mr *MockUserRepoMockRecorder) UpdateLanguages(ctx, id, nativeLanguageID, targetLanguageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLanguages", reflect.TypeOf((*MockUserRepo)(nil).UpdateLanguages), ctx, id, nativeLanguageID, targetLanguageID)
}

// UpsertWatchHistory mocks base method.
func (m *MockUserRepo) UpsertWatchHistory(ctx context.Context, userID string, videoID int64, lastPositionSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWatchHistory", ctx, userID, videoID, lastPositionSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWatchHistory indicates an expected call of UpsertWatchHistory.
func (mr *MockUserRepoMockRecorder) UpsertWatchHistory(ctx, userID, videoID, lastPositionSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWatchHistory", reflect.TypeOf((*MockUserRepo)(nil).UpsertWatchHistory), ctx, userID, videoID, lastPositionSeconds)
}

// MockLanguageRepo is a mock of LanguageRepo interface.
type MockLanguageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageRepoMockRecorder
	isgomock struct{}
}

// MockLanguageRepoMockRecorder is the mock recorder for MockLanguageRepo.
type MockLanguageRepoMockRecorder struct {
	mock *MockLanguageRepo
}

// NewMockLanguageRepo creates a new mock instance.
func NewMockLanguageRepo(ctrl *gomock.Controller) *MockLanguageRepo {
	mock := &MockLanguageRepo{ctrl: ctrl}
	mock.recorder = &MockLanguageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguageRepo) EXPECT() *MockLanguageRepoMockRecorder {
	return m.recorder
}

// CreateLanguage mocks base method.
func (m *MockLanguageRepo) CreateLanguage(ctx context.Context, language *entity.Language) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLanguage", ctx, language)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLanguage indicates an expected call of CreateLanguage.
func (mr *MockLanguageRepoMockRecorder) CreateLanguage(ctx, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLanguage", reflect.TypeOf((*MockLanguageRepo)(nil).CreateLanguage), ctx, language)
}

// GetLanguage mocks base method.
func (m *MockLanguageRepo) GetLanguage(ctx context.Context, id int) (entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguage", ctx, id)
	ret0, _ := ret[0].(entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLanguage indicates an expected call of GetLanguage.
func (mr *MockLanguageRepoMockRecorder) GetLanguage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguage", reflect.TypeOf((*MockLanguageRepo)(nil).GetLanguage), ctx, id)
}

// GetLanguageByCode mocks base method.
func (m *MockLanguageRepo) GetLanguageByCode(ctx context.Context, code string) (entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguageByCode", ctx, code)
	ret0, _ := ret[0].(entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLanguageByCode indicates an expected call of GetLanguageByCode.
func (mr *MockLanguageRepoMockRecorder) GetLanguageByCode(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguageByCode", reflect.TypeOf((*MockLanguageRepo)(nil).GetLanguageByCode), ctx, code)
}

// ListLanguages mocks base method.
func (m *MockLanguageRepo) ListLanguages(ctx context.Context) ([]entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx)
	ret0, _ := ret[0].([]entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockLanguageRepoMockRecorder) ListLanguages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockLanguageRepo)(nil).ListLanguages), ctx)
}

// UpdateLanguage mocks base method.
func (m *MockLanguageRepo) UpdateLanguage(ctx context.Context, language *entity.Language) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLanguage", ctx, language)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLanguage indicates an expected call of UpdateLanguage.
func (mr *MockLanguageRepoMockRecorder) UpdateLanguage(ctx, language any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLanguage", reflect.TypeOf((*MockLanguageRepo)(nil).UpdateLanguage), ctx, language)
}

// MockLevelRepo is a mock of LevelRepo interface.
type MockLevelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLevelRepoMockRecorder
	isgomock struct{}
}

// MockLevelRepoMockRecorder is the mock recorder for MockLevelRepo.
type MockLevelRepoMockRecorder struct {
	mock *MockLevelRepo
}

// NewMockLevelRepo creates a new mock instance.
func NewMockLevelRepo(ctrl *gomock.Controller) *MockLevelRepo {
	mock := &MockLevelRepo{ctrl: ctrl}
	mock.recorder = &MockLevelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLevelRepo) EXPECT() *MockLevelRepoMockRecorder {
	return m.recorder
}

// CreateLevel mocks base method.
func (m *MockLevelRepo) CreateLevel(ctx context.Context, level *entity.Level) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLevel", ctx, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLevel indicates an expected call of CreateLevel.
func (mr *MockLevelRepoMockRecorder) CreateLevel(ctx, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLevel", reflect.TypeOf((*MockLevelRepo)(nil).CreateLevel), ctx, level)
}

// DeleteLevel mocks base method.
func (m *MockLevelRepo) DeleteLevel(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLevel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLevel indicates an expected call of DeleteLevel.
func (mr *MockLevelRepoMockRecorder) DeleteLevel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLevel", reflect.TypeOf((*MockLevelRepo)(nil).DeleteLevel), ctx, id)
}

// ListLevels mocks base method.
func (m *MockLevelRepo) ListLevels(ctx context.Context, languageID *int) ([]entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLevels", ctx, languageID)
	ret0, _ := ret[0].([]entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLevels indicates an expected call of ListLevels.
func (mr *MockLevelRepoMockRecorder) ListLevels(ctx, languageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLevels", reflect.TypeOf((*MockLevelRepo)(nil).ListLevels), ctx, languageID)
}

// UpdateLevel mocks base method.
func (m *MockLevelRepo) UpdateLevel(ctx context.Context, level *entity.Level) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLevel", ctx, level)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLevel indicates an expected call of UpdateLevel.
func (mr *MockLevelRepoMockRecorder) UpdateLevel(ctx, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLevel", reflect.TypeOf((*MockLevelRepo)(nil).UpdateLevel), ctx, level)
}

// MockTopicRepo is a mock of TopicRepo interface.
type MockTopicRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTopicRepoMockRecorder
	isgomock struct{}
}

// MockTopicRepoMockRecorder is the mock recorder for MockTopicRepo.
type MockTopicRepoMockRecorder struct {
	mock *MockTopicRepo
}

// NewMockTopicRepo creates a new mock instance.
func NewMockTopicRepo(ctrl *gomock.Controller) *MockTopicRepo {
	mock := &MockTopicRepo{ctrl: ctrl}
	mock.recorder = &MockTopicRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicRepo) EXPECT() *MockTopicRepoMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method.
func (m *MockTopicRepo) CreateTopic(ctx context.Context, topic *entity.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockTopicRepoMockRecorder) CreateTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockTopicRepo)(nil).CreateTopic), ctx, topic)
}

// DeleteTopic mocks base method.
func (m *MockTopicRepo) DeleteTopic(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockTopicRepoMockRecorder) DeleteTopic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockTopicRepo)(nil).DeleteTopic), ctx, id)
}

// ListTopics mocks base method.
func (m *MockTopicRepo) ListTopics(ctx context.Context) ([]entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx)
	ret0, _ := ret[0].([]entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockTopicRepoMockRecorder) ListTopics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockTopicRepo)(nil).ListTopics), ctx)
}

// SetTopicActive mocks base method.
func (m *MockTopicRepo) SetTopicActive(ctx context.Context, id int, isActive bool) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTopicActive", ctx, id, isActive)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTopicActive indicates an expected call of SetTopicActive.
func (mr *MockTopicRepoMockRecorder) SetTopicActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopicActive", reflect.TypeOf((*MockTopicRepo)(nil).SetTopicActive), ctx, id, isActive)
}

// UpdateTopic mocks base method.
func (m *MockTopicRepo) UpdateTopic(ctx context.Context, topic *entity.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTopic", ctx, topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTopic indicates an expected call of UpdateTopic.
func (mr *MockTopicRepoMockRecorder) UpdateTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTopic", reflect.TypeOf((*MockTopicRepo)(nil).UpdateTopic), ctx, topic)
}

// MockChannelRepo is a mock of ChannelRepo interface.
type MockChannelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockChannelRepoMockRecorder
	isgomock struct{}
}

// MockChannelRepoMockRecorder is the mock recorder for MockChannelRepo.
type MockChannelRepoMockRecorder struct {
	mock *MockChannelRepo
}

// NewMockChannelRepo creates a new mock instance.
func NewMockChannelRepo(ctrl *gomock.Controller) *MockChannelRepo {
	mock := &MockChannelRepo{ctrl: ctrl}
	mock.recorder = &MockChannelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelRepo) EXPECT() *MockChannelRepoMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockChannelRepo) CreateChannel(ctx context.Context, channel *entity.Channel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", ctx, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockChannelRepoMockRecorder) CreateChannel(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockChannelRepo)(nil).CreateChannel), ctx, channel)
}

// DeleteChannel mocks base method.
func (m *MockChannelRepo) DeleteChannel(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockChannelRepoMockRecorder) DeleteChannel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockChannelRepo)(nil).DeleteChannel), ctx, id)
}

// ListChannels mocks base method.
func (m *MockChannelRepo) ListChannels(ctx context.Context) ([]entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", ctx)
	ret0, _ := ret[0].([]entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockChannelRepoMockRecorder) ListChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockChannelRepo)(nil).ListChannels), ctx)
}

// UpdateChannel mocks base method.
func (m *MockChannelRepo) UpdateChannel(ctx context.Context, channel *entity.Channel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", ctx, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockChannelRepoMockRecorder) UpdateChannel(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockChannelRepo)(nil).UpdateChannel), ctx, channel)
}

// MockAdminUserRepo is a mock of AdminUserRepo interface.
type MockAdminUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserRepoMockRecorder
	isgomock struct{}
}

// MockAdminUserRepoMockRecorder is the mock recorder for MockAdminUserRepo.
type MockAdminUserRepoMockRecorder struct {
	mock *MockAdminUserRepo
}

// NewMockAdminUserRepo creates a new mock instance.
func NewMockAdminUserRepo(ctrl *gomock.Controller) *MockAdminUserRepo {
	mock := &MockAdminUserRepo{ctrl: ctrl}
	mock.recorder = &MockAdminUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserRepo) EXPECT() *MockAdminUserRepoMockRecorder {
	return m.recorder
}

// ListUsers mocks base method.
func (m *MockAdminUserRepo) ListUsers(ctx context.Context, filter entity.UserFilter) (entity.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, filter)
	ret0, _ := ret[0].(entity.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminUserRepoMockRecorder) ListUsers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminUserRepo)(nil).ListUsers), ctx, filter)
}

// SetUserActive mocks base method.
func (m *MockAdminUserRepo) SetUserActive(ctx context.Context, id string, isActive bool) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActive", ctx, id, isActive)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActive indicates an expected call of SetUserActive.
func (mr *MockAdminUserRepoMockRecorder) SetUserActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActive", reflect.TypeOf((*MockAdminUserRepo)(nil).SetUserActive), ctx, id, isActive)
}

// SetUserRole mocks base method.
func (m *MockAdminUserRepo) SetUserRole(ctx context.Context, id, role string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserRole", ctx, id, role)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserRole indicates an expected call of SetUserRole.
func (mr *MockAdminUserRepoMockRecorder) SetUserRole(ctx, id, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserRole", reflect.TypeOf((*MockAdminUserRepo)(nil).SetUserRole), ctx, id, role)
}

// MockVideoRepo is a mock of VideoRepo interface.
type MockVideoRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVideoRepoMockRecorder
	isgomock struct{}
}

// MockVideoRepoMockRecorder is the mock recorder for MockVideoRepo.
type MockVideoRepoMockRecorder struct {
	mock *MockVideoRepo
}

// NewMockVideoRepo creates a new mock instance.
func NewMockVideoRepo(ctrl *gomock.Controller) *MockVideoRepo {
	mock := &MockVideoRepo{ctrl: ctrl}
	mock.recorder = &MockVideoRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoRepo) EXPECT() *MockVideoRepoMockRecorder {
	return m.recorder
}

// CreateVideo mocks base method.
func (m *MockVideoRepo) CreateVideo(ctx context.Context, input entity.VideoInput) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideo", ctx, input)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVideo indicates an expected call of CreateVideo.
func (mr *MockVideoRepoMockRecorder) CreateVideo(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideo", reflect.TypeOf((*MockVideoRepo)(nil).CreateVideo), ctx, input)
}

// DeleteVideo mocks base method.
func (m *MockVideoRepo) DeleteVideo(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVideo", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVideo indicates an expected call of DeleteVideo.
func (mr *MockVideoRepoMockRecorder) DeleteVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideo", reflect.TypeOf((*MockVideoRepo)(nil).DeleteVideo), ctx, id)
}

// GetVideo mocks base method.
func (m *MockVideoRepo) GetVideo(ctx context.Context, id int64) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideo", ctx, id)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideo indicates an expected call of GetVideo.
func (mr *MockVideoRepoMockRecorder) GetVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideo", reflect.TypeOf((*MockVideoRepo)(nil).GetVideo), ctx, id)
}

// ListUserVideos mocks base method.
func (m *MockVideoRepo) ListUserVideos(ctx context.Context, userID string, limit, offset int) (entity.VideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserVideos", ctx, userID, limit, offset)
	ret0, _ := ret[0].(entity.VideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserVideos indicates an expected call of ListUserVideos.
func (mr *MockVideoRepoMockRecorder) ListUserVideos(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserVideos", reflect.TypeOf((*MockVideoRepo)(nil).ListUserVideos), ctx, userID, limit, offset)
}

// ListVideos mocks base method.
func (m *MockVideoRepo) ListVideos(ctx context.Context, filter entity.VideoFilter) (entity.VideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideos", ctx, filter)
	ret0, _ := ret[0].(entity.VideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideos indicates an expected call of ListVideos.
func (mr *MockVideoRepoMockRecorder) ListVideos(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideos", reflect.TypeOf((*MockVideoRepo)(nil).ListVideos), ctx, filter)
}

// RemoveUserVideo mocks base method.
func (m *MockVideoRepo) RemoveUserVideo(ctx context.Context, userID string, videoID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserVideo", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserVideo indicates an expected call of RemoveUserVideo.
func (mr *MockVideoRepoMockRecorder) RemoveUserVideo(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserVideo", reflect.TypeOf((*MockVideoRepo)(nil).RemoveUserVideo), ctx, userID, videoID)
}

// SetVideoStatus mocks base method.
func (m *MockVideoRepo) SetVideoStatus(ctx context.Context, id int64, expectedStatus, nextStatus string) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVideoStatus", ctx, id, expectedStatus, nextStatus)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetVideoStatus indicates an expected call of SetVideoStatus.
func (mr *MockVideoRepoMockRecorder) SetVideoStatus(ctx, id, expectedStatus, nextStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVideoStatus", reflect.TypeOf((*MockVideoRepo)(nil).SetVideoStatus), ctx, id, expectedStatus, nextStatus)
}

// UpdateVideo mocks base method.
func (m *MockVideoRepo) UpdateVideo(ctx context.Context, id int64, input entity.VideoInput) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideo", ctx, id, input)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVideo indicates an expected call of UpdateVideo.
func (mr *MockVideoRepoMockRecorder) UpdateVideo(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideo", reflect.TypeOf((*MockVideoRepo)(nil).UpdateVideo), ctx, id, input)
}

// UpdateVideoLanguage mocks base method.
func (m *MockVideoRepo) UpdateVideoLanguage(ctx context.Context, id int64, languageID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideoLanguage", ctx, id, languageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideoLanguage indicates an expected call of UpdateVideoLanguage.
func (mr *MockVideoRepoMockRecorder) UpdateVideoLanguage(ctx, id, languageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideoLanguage", reflect.TypeOf((*MockVideoRepo)(nil).UpdateVideoLanguage), ctx, id, languageID)
}

// UpsertUserVideo mocks base method.
func (m *MockVideoRepo) UpsertUserVideo(ctx context.Context, userID string, preview entity.YouTubeVideoPreview, languageID int) (entity.Video, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserVideo", ctx, userID, preview, languageID)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertUserVideo indicates an expected call of UpsertUserVideo.
func (mr *MockVideoRepoMockRecorder) UpsertUserVideo(ctx, userID, preview, languageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserVideo", reflect.TypeOf((*MockVideoRepo)(nil).UpsertUserVideo), ctx, userID, preview, languageID)
}

// MockCaptionRepo is a mock of CaptionRepo interface.
type MockCaptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCaptionRepoMockRecorder
	isgomock struct{}
}

// MockCaptionRepoMockRecorder is the mock recorder for MockCaptionRepo.
type MockCaptionRepoMockRecorder struct {
	mock *MockCaptionRepo
}

// NewMockCaptionRepo creates a new mock instance.
func NewMockCaptionRepo(ctrl *gomock.Controller) *MockCaptionRepo {
	mock := &MockCaptionRepo{ctrl: ctrl}
	mock.recorder = &MockCaptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaptionRepo) EXPECT() *MockCaptionRepoMockRecorder {
	return m.recorder
}

// CreateCaption mocks base method.
func (m *MockCaptionRepo) CreateCaption(ctx context.Context, videoID int64, input entity.CaptionInput) (entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCaption", ctx, videoID, input)
	ret0, _ := ret[0].(entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCaption indicates an expected call of CreateCaption.
func (mr *MockCaptionRepoMockRecorder) CreateCaption(ctx, videoID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCaption", reflect.TypeOf((*MockCaptionRepo)(nil).CreateCaption), ctx, videoID, input)
}

// DeleteCaption mocks base method.
func (m *MockCaptionRepo) DeleteCaption(ctx context.Context, videoID, captionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCaption", ctx, videoID, captionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCaption indicates an expected call of DeleteCaption.
func (mr *MockCaptionRepoMockRecorder) DeleteCaption(ctx, videoID, captionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCaption", reflect.TypeOf((*MockCaptionRepo)(nil).DeleteCaption), ctx, videoID, captionID)
}

// ImportCaptions mocks base method.
func (m *MockCaptionRepo) ImportCaptions(ctx context.Context, videoID int64, inputs []entity.CaptionInput) ([]entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCaptions", ctx, videoID, inputs)
	ret0, _ := ret[0].([]entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportCaptions indicates an expected call of ImportCaptions.
func (mr *MockCaptionRepoMockRecorder) ImportCaptions(ctx, videoID, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCaptions", reflect.TypeOf((*MockCaptionRepo)(nil).ImportCaptions), ctx, videoID, inputs)
}

// ImportCaptionsIfEmpty mocks base method.
func (m *MockCaptionRepo) ImportCaptionsIfEmpty(ctx context.Context, videoID int64, inputs []entity.CaptionInput) ([]entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportCaptionsIfEmpty", ctx, videoID, inputs)
	ret0, _ := ret[0].([]entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportCaptionsIfEmpty indicates an expected call of ImportCaptionsIfEmpty.
func (mr *MockCaptionRepoMockRecorder) ImportCaptionsIfEmpty(ctx, videoID, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportCaptionsIfEmpty", reflect.TypeOf((*MockCaptionRepo)(nil).ImportCaptionsIfEmpty), ctx, videoID, inputs)
}

// ListCaptions mocks base method.
func (m *MockCaptionRepo) ListCaptions(ctx context.Context, videoID int64, filter entity.CaptionFilter) (entity.CaptionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCaptions", ctx, videoID, filter)
	ret0, _ := ret[0].(entity.CaptionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCaptions indicates an expected call of ListCaptions.
func (mr *MockCaptionRepoMockRecorder) ListCaptions(ctx, videoID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCaptions", reflect.TypeOf((*MockCaptionRepo)(nil).ListCaptions), ctx, videoID, filter)
}

// ListCaptionsForTranslation mocks base method.
func (m *MockCaptionRepo) ListCaptionsForTranslation(ctx context.Context, videoID int64, targetLanguageID int, missingOnly bool) ([]entity.Caption, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCaptionsForTranslation", ctx, videoID, targetLanguageID, missingOnly)
	ret0, _ := ret[0].([]entity.Caption)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCaptionsForTranslation indicates an expected call of ListCaptionsForTranslation.
func (mr *MockCaptionRepoMockRecorder) ListCaptionsForTranslation(ctx, videoID, targetLanguageID, missingOnly any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCaptionsForTranslation", reflect.TypeOf((*MockCaptionRepo)(nil).ListCaptionsForTranslation), ctx, videoID, targetLanguageID, missingOnly)
}

// ReplaceCaptions mocks base method.
func (m *MockCaptionRepo) ReplaceCaptions(ctx context.Context, videoID int64, inputs []entity.CaptionInput) ([]entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceCaptions", ctx, videoID, inputs)
	ret0, _ := ret[0].([]entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceCaptions indicates an expected call of ReplaceCaptions.
func (mr *MockCaptionRepoMockRecorder) ReplaceCaptions(ctx, videoID, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceCaptions", reflect.TypeOf((*MockCaptionRepo)(nil).ReplaceCaptions), ctx, videoID, inputs)
}

// UpdateCaption mocks base method.
func (m *MockCaptionRepo) UpdateCaption(ctx context.Context, videoID, captionID int64, input entity.CaptionInput) (entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCaption", ctx, videoID, captionID, input)
	ret0, _ := ret[0].(entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCaption indicates an expected call of UpdateCaption.
func (mr *MockCaptionRepoMockRecorder) UpdateCaption(ctx, videoID, captionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCaption", reflect.TypeOf((*MockCaptionRepo)(nil).UpdateCaption), ctx, videoID, captionID, input)
}

// UpsertTranslations mocks base method.
func (m *MockCaptionRepo) UpsertTranslations(ctx context.Context, videoID int64, languageID int, items []entity.CaptionTranslationUpsert) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTranslations", ctx, videoID, languageID, items)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTranslations indicates an expected call of UpsertTranslations.
func (mr *MockCaptionRepoMockRecorder) UpsertTranslations(ctx, videoID, languageID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTranslations", reflect.TypeOf((*MockCaptionRepo)(nil).UpsertTranslations), ctx, videoID, languageID, items)
}

// MockDictionaryRepo is a mock of DictionaryRepo interface.
type MockDictionaryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDictionaryRepoMockRecorder
	isgomock struct{}
}

// MockDictionaryRepoMockRecorder is the mock recorder for MockDictionaryRepo.
type MockDictionaryRepoMockRecorder struct {
	mock *MockDictionaryRepo
}

// NewMockDictionaryRepo creates a new mock instance.
func NewMockDictionaryRepo(ctrl *gomock.Controller) *MockDictionaryRepo {
	mock := &MockDictionaryRepo{ctrl: ctrl}
	mock.recorder = &MockDictionaryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDictionaryRepo) EXPECT() *MockDictionaryRepoMockRecorder {
	return m.recorder
}

// CreateUserVocabulary mocks base method.
func (m *MockDictionaryRepo) CreateUserVocabulary(ctx context.Context, userID string, input entity.UserVocabularyInput, languages entity.VocabularyLanguages) (entity.UserVocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserVocabulary", ctx, userID, input, languages)
	ret0, _ := ret[0].(entity.UserVocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserVocabulary indicates an expected call of CreateUserVocabulary.
func (mr *MockDictionaryRepoMockRecorder) CreateUserVocabulary(ctx, userID, input, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserVocabulary", reflect.TypeOf((*MockDictionaryRepo)(nil).CreateUserVocabulary), ctx, userID, input, languages)
}

// CreateVocabularySet mocks base method.
func (m *MockDictionaryRepo) CreateVocabularySet(ctx context.Context, userID, title, colorHex string, languages entity.VocabularyLanguages) (entity.VocabularySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVocabularySet", ctx, userID, title, colorHex, languages)
	ret0, _ := ret[0].(entity.VocabularySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVocabularySet indicates an expected call of CreateVocabularySet.
func (mr *MockDictionaryRepoMockRecorder) CreateVocabularySet(ctx, userID, title, colorHex, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVocabularySet", reflect.TypeOf((*MockDictionaryRepo)(nil).CreateVocabularySet), ctx, userID, title, colorHex, languages)
}

// DeleteUserVocabulary mocks base method.
func (m *MockDictionaryRepo) DeleteUserVocabulary(ctx context.Context, userID string, id int64, languages entity.VocabularyLanguages) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserVocabulary", ctx, userID, id, languages)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserVocabulary indicates an expected call of DeleteUserVocabulary.
func (mr *MockDictionaryRepoMockRecorder) DeleteUserVocabulary(ctx, userID, id, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserVocabulary", reflect.TypeOf((*MockDictionaryRepo)(nil).DeleteUserVocabulary), ctx, userID, id, languages)
}

// DeleteVocabularySet mocks base method.
func (m *MockDictionaryRepo) DeleteVocabularySet(ctx context.Context, userID string, id int64, languages entity.VocabularyLanguages) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVocabularySet", ctx, userID, id, languages)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVocabularySet indicates an expected call of DeleteVocabularySet.
func (mr *MockDictionaryRepoMockRecorder) DeleteVocabularySet(ctx, userID, id, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVocabularySet", reflect.TypeOf((*MockDictionaryRepo)(nil).DeleteVocabularySet), ctx, userID, id, languages)
}

// FindDictionaryEntry mocks base method.
func (m *MockDictionaryRepo) FindDictionaryEntry(ctx context.Context, word string, sourceLanguageID, targetLanguageID int) (entity.DictionaryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDictionaryEntry", ctx, word, sourceLanguageID, targetLanguageID)
	ret0, _ := ret[0].(entity.DictionaryEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDictionaryEntry indicates an expected call of FindDictionaryEntry.
func (mr *MockDictionaryRepoMockRecorder) FindDictionaryEntry(ctx, word, sourceLanguageID, targetLanguageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDictionaryEntry", reflect.TypeOf((*MockDictionaryRepo)(nil).FindDictionaryEntry), ctx, word, sourceLanguageID, targetLanguageID)
}

// GetVocabularyOverview mocks base method.
func (m *MockDictionaryRepo) GetVocabularyOverview(ctx context.Context, userID string, languages entity.VocabularyLanguages) (entity.VocabularyOverview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVocabularyOverview", ctx, userID, languages)
	ret0, _ := ret[0].(entity.VocabularyOverview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVocabularyOverview indicates an expected call of GetVocabularyOverview.
func (mr *MockDictionaryRepoMockRecorder) GetVocabularyOverview(ctx, userID, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVocabularyOverview", reflect.TypeOf((*MockDictionaryRepo)(nil).GetVocabularyOverview), ctx, userID, languages)
}

// ListUnlearnedVocabularies mocks base method.
func (m *MockDictionaryRepo) ListUnlearnedVocabularies(ctx context.Context, userID string, filter entity.UnlearnedVocabularyFilter, languages entity.VocabularyLanguages) ([]entity.UserVocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnlearnedVocabularies", ctx, userID, filter, languages)
	ret0, _ := ret[0].([]entity.UserVocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnlearnedVocabularies indicates an expected call of ListUnlearnedVocabularies.
func (mr *MockDictionaryRepoMockRecorder) ListUnlearnedVocabularies(ctx, userID, filter, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnlearnedVocabularies", reflect.TypeOf((*MockDictionaryRepo)(nil).ListUnlearnedVocabularies), ctx, userID, filter, languages)
}

// ListUserVocabularies mocks base method.
func (m *MockDictionaryRepo) ListUserVocabularies(ctx context.Context, userID string, filter entity.UserVocabularyFilter, languages entity.VocabularyLanguages) ([]entity.UserVocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserVocabularies", ctx, userID, filter, languages)
	ret0, _ := ret[0].([]entity.UserVocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserVocabularies indicates an expected call of ListUserVocabularies.
func (mr *MockDictionaryRepoMockRecorder) ListUserVocabularies(ctx, userID, filter, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserVocabularies", reflect.TypeOf((*MockDictionaryRepo)(nil).ListUserVocabularies), ctx, userID, filter, languages)
}

// ListVocabularySets mocks base method.
func (m *MockDictionaryRepo) ListVocabularySets(ctx context.Context, userID string, languages entity.VocabularyLanguages) ([]entity.VocabularySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVocabularySets", ctx, userID, languages)
	ret0, _ := ret[0].([]entity.VocabularySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVocabularySets indicates an expected call of ListVocabularySets.
func (mr *MockDictionaryRepoMockRecorder) ListVocabularySets(ctx, userID, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVocabularySets", reflect.TypeOf((*MockDictionaryRepo)(nil).ListVocabularySets), ctx, userID, languages)
}

// UpdateUserVocabulary mocks base method.
func (m *MockDictionaryRepo) UpdateUserVocabulary(ctx context.Context, userID string, id int64, input entity.UserVocabularyUpdate, languages entity.VocabularyLanguages) (entity.UserVocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserVocabulary", ctx, userID, id, input, languages)
	ret0, _ := ret[0].(entity.UserVocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserVocabulary indicates an expected call of UpdateUserVocabulary.
func (mr *MockDictionaryRepoMockRecorder) UpdateUserVocabulary(ctx, userID, id, input, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserVocabulary", reflect.TypeOf((*MockDictionaryRepo)(nil).UpdateUserVocabulary), ctx, userID, id, input, languages)
}

// UpdateVocabularySet mocks base method.
func (m *MockDictionaryRepo) UpdateVocabularySet(ctx context.Context, userID string, id int64, title, colorHex string, languages entity.VocabularyLanguages) (entity.VocabularySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVocabularySet", ctx, userID, id, title, colorHex, languages)
	ret0, _ := ret[0].(entity.VocabularySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVocabularySet indicates an expected call of UpdateVocabularySet.
func (mr *MockDictionaryRepoMockRecorder) UpdateVocabularySet(ctx, userID, id, title, colorHex, languages any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVocabularySet", reflect.TypeOf((*MockDictionaryRepo)(nil).UpdateVocabularySet), ctx, userID, id, title, colorHex, languages)
}

// UpsertDictionaryEntry mocks base method.
func (m *MockDictionaryRepo) UpsertDictionaryEntry(ctx context.Context, input entity.DictionaryInput) (entity.DictionaryEntry, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertDictionaryEntry", ctx, input)
	ret0, _ := ret[0].(entity.DictionaryEntry)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertDictionaryEntry indicates an expected call of UpsertDictionaryEntry.
func (mr *MockDictionaryRepoMockRecorder) UpsertDictionaryEntry(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertDictionaryEntry", reflect.TypeOf((*MockDictionaryRepo)(nil).UpsertDictionaryEntry), ctx, input)
}

// MockLearningContentRepo is a mock of LearningContentRepo interface.
type MockLearningContentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLearningContentRepoMockRecorder
	isgomock struct{}
}

// MockLearningContentRepoMockRecorder is the mock recorder for MockLearningContentRepo.
type MockLearningContentRepoMockRecorder struct {
	mock *MockLearningContentRepo
}

// NewMockLearningContentRepo creates a new mock instance.
func NewMockLearningContentRepo(ctrl *gomock.Controller) *MockLearningContentRepo {
	mock := &MockLearningContentRepo{ctrl: ctrl}
	mock.recorder = &MockLearningContentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLearningContentRepo) EXPECT() *MockLearningContentRepoMockRecorder {
	return m.recorder
}

// GetLocalizedLearningContent mocks base method.
func (m *MockLearningContentRepo) GetLocalizedLearningContent(ctx context.Context, videoID int64, languageID int) (entity.VideoSummary, []entity.DictionaryEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalizedLearningContent", ctx, videoID, languageID)
	ret0, _ := ret[0].(entity.VideoSummary)
	ret1, _ := ret[1].([]entity.DictionaryEntry)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLocalizedLearningContent indicates an expected call of GetLocalizedLearningContent.
func (mr *MockLearningContentRepoMockRecorder) GetLocalizedLearningContent(ctx, videoID, languageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalizedLearningContent", reflect.TypeOf((*MockLearningContentRepo)(nil).GetLocalizedLearningContent), ctx, videoID, languageID)
}

// GetQuizzes mocks base method.
func (m *MockLearningContentRepo) GetQuizzes(ctx context.Context, videoID int64) ([]entity.LearningQuiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuizzes", ctx, videoID)
	ret0, _ := ret[0].([]entity.LearningQuiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuizzes indicates an expected call of GetQuizzes.
func (mr *MockLearningContentRepoMockRecorder) GetQuizzes(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuizzes", reflect.TypeOf((*MockLearningContentRepo)(nil).GetQuizzes), ctx, videoID)
}

// SaveLocalizedLearningContentIfAbsent mocks base method.
func (m *MockLearningContentRepo) SaveLocalizedLearningContentIfAbsent(ctx context.Context, summary entity.VideoSummary, dictionaryIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveLocalizedLearningContentIfAbsent", ctx, summary, dictionaryIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveLocalizedLearningContentIfAbsent indicates an expected call of SaveLocalizedLearningContentIfAbsent.
func (mr *MockLearningContentRepoMockRecorder) SaveLocalizedLearningContentIfAbsent(ctx, summary, dictionaryIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLocalizedLearningContentIfAbsent", reflect.TypeOf((*MockLearningContentRepo)(nil).SaveLocalizedLearningContentIfAbsent), ctx, summary, dictionaryIDs)
}

// SaveQuizzesIfAbsent mocks base method.
func (m *MockLearningContentRepo) SaveQuizzesIfAbsent(ctx context.Context, videoID int64, quizzes []entity.GeneratedQuiz) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveQuizzesIfAbsent", ctx, videoID, quizzes)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveQuizzesIfAbsent indicates an expected call of SaveQuizzesIfAbsent.
func (mr *MockLearningContentRepoMockRecorder) SaveQuizzesIfAbsent(ctx, videoID, quizzes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveQuizzesIfAbsent", reflect.TypeOf((*MockLearningContentRepo)(nil).SaveQuizzesIfAbsent), ctx, videoID, quizzes)
}

// MockShadowingRepo is a mock of ShadowingRepo interface.
type MockShadowingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShadowingRepoMockRecorder
	isgomock struct{}
}

// MockShadowingRepoMockRecorder is the mock recorder for MockShadowingRepo.
type MockShadowingRepoMockRecorder struct {
	mock *MockShadowingRepo
}

// NewMockShadowingRepo creates a new mock instance.
func NewMockShadowingRepo(ctrl *gomock.Controller) *MockShadowingRepo {
	mock := &MockShadowingRepo{ctrl: ctrl}
	mock.recorder = &MockShadowingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShadowingRepo) EXPECT() *MockShadowingRepoMockRecorder {
	return m.recorder
}

// GetPrompt mocks base method.
func (m *MockShadowingRepo) GetPrompt(ctx context.Context, videoID, captionID int64) (entity.ShadowingPrompt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrompt", ctx, videoID, captionID)
	ret0, _ := ret[0].(entity.ShadowingPrompt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrompt indicates an expected call of GetPrompt.
func (mr *MockShadowingRepoMockRecorder) GetPrompt(ctx, videoID, captionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrompt", reflect.TypeOf((*MockShadowingRepo)(nil).GetPrompt), ctx, videoID, captionID)
}

// ListAttempts mocks base method.
func (m *MockShadowingRepo) ListAttempts(ctx context.Context, userID string, videoID, captionID int64) (entity.ShadowingAttemptList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttempts", ctx, userID, videoID, captionID)
	ret0, _ := ret[0].(entity.ShadowingAttemptList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttempts indicates an expected call of ListAttempts.
func (mr *MockShadowingRepoMockRecorder) ListAttempts(ctx, userID, videoID, captionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttempts", reflect.TypeOf((*MockShadowingRepo)(nil).ListAttempts), ctx, userID, videoID, captionID)
}

// SaveAttempt mocks base method.
func (m *MockShadowingRepo) SaveAttempt(ctx context.Context, userID string, prompt entity.ShadowingPrompt, assessment entity.PronunciationAssessment) (entity.ShadowingAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAttempt", ctx, userID, prompt, assessment)
	ret0, _ := ret[0].(entity.ShadowingAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAttempt indicates an expected call of SaveAttempt.
func (mr *MockShadowingRepoMockRecorder) SaveAttempt(ctx, userID, prompt, assessment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAttempt", reflect.TypeOf((*MockShadowingRepo)(nil).SaveAttempt), ctx, userID, prompt, assessment)
}

// MockQuotaRepo is a mock of QuotaRepo interface.
type MockQuotaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaRepoMockRecorder
	isgomock struct{}
}

// MockQuotaRepoMockRecorder is the mock recorder for MockQuotaRepo.
type MockQuotaRepoMockRecorder struct {
	mock *MockQuotaRepo
}

// NewMockQuotaRepo creates a new mock instance.
func NewMockQuotaRepo(ctrl *gomock.Controller) *MockQuotaRepo {
	mock := &MockQuotaRepo{ctrl: ctrl}
	mock.recorder = &MockQuotaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaRepo) EXPECT() *MockQuotaRepoMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockQuotaRepo) Consume(ctx context.Context, userID string, feature entity.FeatureKey, windowStart time.Time, limit int) (int, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, userID, feature, windowStart, limit)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Consume indicates an expected call of Consume.
func (mr *MockQuotaRepoMockRecorder) Consume(ctx, userID, feature, windowStart, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockQuotaRepo)(nil).Consume), ctx, userID, feature, windowStart, limit)
}
