// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source internal/usecase/contracts.go -destination internal/usecase/mocks_usecase_test.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockUser) Authenticate(ctx context.Context, identity entity.AuthIdentity) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, identity)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockUserMockRecorder) Authenticate(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockUser)(nil).Authenticate), ctx, identity)
}

// CompleteDictation mocks base method.
func (m *MockUser) CompleteDictation(ctx context.Context, userID string, videoID, captionID int64) (entity.DictationProgress, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteDictation", ctx, userID, videoID, captionID)
	ret0, _ := ret[0].(entity.DictationProgress)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteDictation indicates an expected call of CompleteDictation.
func (mr *MockUserMockRecorder) CompleteDictation(ctx, userID, videoID, captionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteDictation", reflect.TypeOf((*MockUser)(nil).CompleteDictation), ctx, userID, videoID, captionID)
}

// GetUser mocks base method.
func (m *MockUser) GetUser(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUser)(nil).GetUser), ctx, userID)
}

// GetVideoState mocks base method.
func (m *MockUser) GetVideoState(ctx context.Context, userID string, videoID int64) (entity.VideoState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideoState", ctx, userID, videoID)
	ret0, _ := ret[0].(entity.VideoState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideoState indicates an expected call of GetVideoState.
func (mr *MockUserMockRecorder) GetVideoState(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoState", reflect.TypeOf((*MockUser)(nil).GetVideoState), ctx, userID, videoID)
}

// GetWatchHistory mocks base method.
func (m *MockUser) GetWatchHistory(ctx context.Context, userID string, videoID int64) (entity.UserVideo, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchHistory", ctx, userID, videoID)
	ret0, _ := ret[0].(entity.UserVideo)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWatchHistory indicates an expected call of GetWatchHistory.
func (mr *MockUserMockRecorder) GetWatchHistory(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchHistory", reflect.TypeOf((*MockUser)(nil).GetWatchHistory), ctx, userID, videoID)
}

// ListCompletedDictations mocks base method.
func (m *MockUser) ListCompletedDictations(ctx context.Context, userID string, videoID int64) (entity.DictationProgressList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompletedDictations", ctx, userID, videoID)
	ret0, _ := ret[0].(entity.DictationProgressList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompletedDictations indicates an expected call of ListCompletedDictations.
func (mr *MockUserMockRecorder) ListCompletedDictations(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompletedDictations", reflect.TypeOf((*MockUser)(nil).ListCompletedDictations), ctx, userID, videoID)
}

// ListWatchHistory mocks base method.
func (m *MockUser) ListWatchHistory(ctx context.Context, userID string, limit, offset int) (entity.UserVideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWatchHistory", ctx, userID, limit, offset)
	ret0, _ := ret[0].(entity.UserVideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWatchHistory indicates an expected call of ListWatchHistory.
func (mr *MockUserMockRecorder) ListWatchHistory(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWatchHistory", reflect.TypeOf((*MockUser)(nil).ListWatchHistory), ctx, userID, limit, offset)
}

// ListWatchLater mocks base method.
func (m *MockUser) ListWatchLater(ctx context.Context, userID string, limit, offset int) (entity.UserVideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWatchLater", ctx, userID, limit, offset)
	ret0, _ := ret[0].(entity.UserVideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWatchLater indicates an expected call of ListWatchLater.
func (mr *MockUserMockRecorder) ListWatchLater(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWatchLater", reflect.TypeOf((*MockUser)(nil).ListWatchLater), ctx, userID, limit, offset)
}

// Login mocks base method.
func (m *MockUser) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUser)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockUser) Register(ctx context.Context, username, email, password string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserMockRecorder) Register(ctx, username, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUser)(nil).Register), ctx, username, email, password)
}

// RemoveWatchHistory mocks base method.
func (m *MockUser) RemoveWatchHistory(ctx context.Context, userID string, videoID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWatchHistory", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWatchHistory indicates an expected call of RemoveWatchHistory.
func (mr *MockUserMockRecorder) RemoveWatchHistory(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWatchHistory", reflect.TypeOf((*MockUser)(nil).RemoveWatchHistory), ctx, userID, videoID)
}

// RemoveWatchLater mocks base method.
func (m *MockUser) RemoveWatchLater(ctx context.Context, userID string, videoID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWatchLater", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWatchLater indicates an expected call of RemoveWatchLater.
func (mr *MockUserMockRecorder) RemoveWatchLater(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWatchLater", reflect.TypeOf((*MockUser)(nil).RemoveWatchLater), ctx, userID, videoID)
}

// SaveWatchLater mocks base method.
func (m *MockUser) SaveWatchLater(ctx context.Context, userID string, videoID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWatchLater", ctx, userID, videoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWatchLater indicates an expected call of SaveWatchLater.
func (mr *MockUserMockRecorder) SaveWatchLater(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWatchLater", reflect.TypeOf((*MockUser)(nil).SaveWatchLater), ctx, userID, videoID)
}

// UpdateLanguages mocks base method.
func (m *MockUser) UpdateLanguages(ctx context.Context, userID string, nativeLanguageID, targetLanguageID int) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLanguages", ctx, userID, nativeLanguageID, targetLanguageID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLanguages indicates an expected call of UpdateLanguages.
func (mr *MockUserMockRecorder) UpdateLanguages(ctx, userID, nativeLanguageID, targetLanguageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLanguages", reflect.TypeOf((*MockUser)(nil).UpdateLanguages), ctx, userID, nativeLanguageID, targetLanguageID)
}

// UpsertWatchHistory mocks base method.
func (m *MockUser) UpsertWatchHistory(ctx context.Context, userID string, videoID int64, lastPositionSeconds int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWatchHistory", ctx, userID, videoID, lastPositionSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertWatchHistory indicates an expected call of UpsertWatchHistory.
func (mr *MockUserMockRecorder) UpsertWatchHistory(ctx, userID, videoID, lastPositionSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWatchHistory", reflect.TypeOf((*MockUser)(nil).UpsertWatchHistory), ctx, userID, videoID, lastPositionSeconds)
}

// MockLanguage is a mock of Language interface.
type MockLanguage struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageMockRecorder
	isgomock struct{}
}

// MockLanguageMockRecorder is the mock recorder for MockLanguage.
type MockLanguageMockRecorder struct {
	mock *MockLanguage
}

// NewMockLanguage creates a new mock instance.
func NewMockLanguage(ctrl *gomock.Controller) *MockLanguage {
	mock := &MockLanguage{ctrl: ctrl}
	mock.recorder = &MockLanguageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguage) EXPECT() *MockLanguageMockRecorder {
	return m.recorder
}

// CreateLanguage mocks base method.
func (m *MockLanguage) CreateLanguage(ctx context.Context, code, name, flagEmoji string, isLearnable bool) (entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLanguage", ctx, code, name, flagEmoji, isLearnable)
	ret0, _ := ret[0].(entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLanguage indicates an expected call of CreateLanguage.
func (mr *MockLanguageMockRecorder) CreateLanguage(ctx, code, name, flagEmoji, isLearnable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLanguage", reflect.TypeOf((*MockLanguage)(nil).CreateLanguage), ctx, code, name, flagEmoji, isLearnable)
}

// ListLanguages mocks base method.
func (m *MockLanguage) ListLanguages(ctx context.Context) ([]entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx)
	ret0, _ := ret[0].([]entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockLanguageMockRecorder) ListLanguages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockLanguage)(nil).ListLanguages), ctx)
}

// UpdateLanguage mocks base method.
func (m *MockLanguage) UpdateLanguage(ctx context.Context, id int, name, flagEmoji string, isActive, isLearnable bool) (entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLanguage", ctx, id, name, flagEmoji, isActive, isLearnable)
	ret0, _ := ret[0].(entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLanguage indicates an expected call of UpdateLanguage.
func (mr *MockLanguageMockRecorder) UpdateLanguage(ctx, id, name, flagEmoji, isActive, isLearnable any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLanguage", reflect.TypeOf((*MockLanguage)(nil).UpdateLanguage), ctx, id, name, flagEmoji, isActive, isLearnable)
}

// MockLevel is a mock of Level interface.
type MockLevel struct {
	ctrl     *gomock.Controller
	recorder *MockLevelMockRecorder
	isgomock struct{}
}

// MockLevelMockRecorder is the mock recorder for MockLevel.
type MockLevelMockRecorder struct {
	mock *MockLevel
}

// NewMockLevel creates a new mock instance.
func NewMockLevel(ctrl *gomock.Controller) *MockLevel {
	mock := &MockLevel{ctrl: ctrl}
	mock.recorder = &MockLevelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLevel) EXPECT() *MockLevelMockRecorder {
	return m.recorder
}

// CreateLevel mocks base method.
func (m *MockLevel) CreateLevel(ctx context.Context, level entity.Level) (entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLevel", ctx, level)
	ret0, _ := ret[0].(entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLevel indicates an expected call of CreateLevel.
func (mr *MockLevelMockRecorder) CreateLevel(ctx, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLevel", reflect.TypeOf((*MockLevel)(nil).CreateLevel), ctx, level)
}

// DeleteLevel mocks base method.
func (m *MockLevel) DeleteLevel(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLevel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLevel indicates an expected call of DeleteLevel.
func (mr *MockLevelMockRecorder) DeleteLevel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLevel", reflect.TypeOf((*MockLevel)(nil).DeleteLevel), ctx, id)
}

// ListLevels mocks base method.
func (m *MockLevel) ListLevels(ctx context.Context, languageID *int) ([]entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLevels", ctx, languageID)
	ret0, _ := ret[0].([]entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLevels indicates an expected call of ListLevels.
func (mr *MockLevelMockRecorder) ListLevels(ctx, languageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLevels", reflect.TypeOf((*MockLevel)(nil).ListLevels), ctx, languageID)
}

// UpdateLevel mocks base method.
func (m *MockLevel) UpdateLevel(ctx context.Context, id int, level entity.Level) (entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLevel", ctx, id, level)
	ret0, _ := ret[0].(entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLevel indicates an expected call of UpdateLevel.
func (mr *MockLevelMockRecorder) UpdateLevel(ctx, id, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLevel", reflect.TypeOf((*MockLevel)(nil).UpdateLevel), ctx, id, level)
}

// MockTopic is a mock of Topic interface.
type MockTopic struct {
	ctrl     *gomock.Controller
	recorder *MockTopicMockRecorder
	isgomock struct{}
}

// MockTopicMockRecorder is the mock recorder for MockTopic.
type MockTopicMockRecorder struct {
	mock *MockTopic
}

// NewMockTopic creates a new mock instance.
func NewMockTopic(ctrl *gomock.Controller) *MockTopic {
	mock := &MockTopic{ctrl: ctrl}
	mock.recorder = &MockTopicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopic) EXPECT() *MockTopicMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method.
func (m *MockTopic) CreateTopic(ctx context.Context, topic entity.Topic) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, topic)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockTopicMockRecorder) CreateTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockTopic)(nil).CreateTopic), ctx, topic)
}

// DeleteTopic mocks base method.
func (m *MockTopic) DeleteTopic(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockTopicMockRecorder) DeleteTopic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockTopic)(nil).DeleteTopic), ctx, id)
}

// ListTopics mocks base method.
func (m *MockTopic) ListTopics(ctx context.Context) ([]entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx)
	ret0, _ := ret[0].([]entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockTopicMockRecorder) ListTopics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockTopic)(nil).ListTopics), ctx)
}

// SetTopicActive mocks base method.
func (m *MockTopic) SetTopicActive(ctx context.Context, id int, isActive bool) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTopicActive", ctx, id, isActive)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTopicActive indicates an expected call of SetTopicActive.
func (mr *MockTopicMockRecorder) SetTopicActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopicActive", reflect.TypeOf((*MockTopic)(nil).SetTopicActive), ctx, id, isActive)
}

// UpdateTopic mocks base method.
func (m *MockTopic) UpdateTopic(ctx context.Context, id int, topic entity.Topic) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTopic", ctx, id, topic)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTopic indicates an expected call of UpdateTopic.
func (mr *MockTopicMockRecorder) UpdateTopic(ctx, id, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTopic", reflect.TypeOf((*MockTopic)(nil).UpdateTopic), ctx, id, topic)
}

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockChannel) CreateChannel(ctx context.Context, channel entity.Channel) (entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", ctx, channel)
	ret0, _ := ret[0].(entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockChannelMockRecorder) CreateChannel(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockChannel)(nil).CreateChannel), ctx, channel)
}

// DeleteChannel mocks base method.
func (m *MockChannel) DeleteChannel(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockChannelMockRecorder) DeleteChannel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockChannel)(nil).DeleteChannel), ctx, id)
}

// ListChannels mocks base method.
func (m *MockChannel) ListChannels(ctx context.Context) ([]entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", ctx)
	ret0, _ := ret[0].([]entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockChannelMockRecorder) ListChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockChannel)(nil).ListChannels), ctx)
}

// UpdateChannel mocks base method.
func (m *MockChannel) UpdateChannel(ctx context.Context, id int, channel entity.Channel) (entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", ctx, id, channel)
	ret0, _ := ret[0].(entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockChannelMockRecorder) UpdateChannel(ctx, id, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockChannel)(nil).UpdateChannel), ctx, id, channel)
}

// MockAdminUser is a mock of AdminUser interface.
type MockAdminUser struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserMockRecorder
	isgomock struct{}
}

// MockAdminUserMockRecorder is the mock recorder for MockAdminUser.
type MockAdminUserMockRecorder struct {
	mock *MockAdminUser
}

// NewMockAdminUser creates a new mock instance.
func NewMockAdminUser(ctrl *gomock.Controller) *MockAdminUser {
	mock := &MockAdminUser{ctrl: ctrl}
	mock.recorder = &MockAdminUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUser) EXPECT() *MockAdminUserMockRecorder {
	return m.recorder
}

// ListUsers mocks base method.
func (m *MockAdminUser) ListUsers(ctx context.Context, filter entity.UserFilter) (entity.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, filter)
	ret0, _ := ret[0].(entity.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminUserMockRecorder) ListUsers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminUser)(nil).ListUsers), ctx, filter)
}

// SetUserActive mocks base method.
func (m *MockAdminUser) SetUserActive(ctx context.Context, actorID, userID string, isActive bool) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActive", ctx, actorID, userID, isActive)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActive indicates an expected call of SetUserActive.
func (mr *MockAdminUserMockRecorder) SetUserActive(ctx, actorID, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActive", reflect.TypeOf((*MockAdminUser)(nil).SetUserActive), ctx, actorID, userID, isActive)
}

// SetUserRole mocks base method.
func (m *MockAdminUser) SetUserRole(ctx context.Context, actorID, userID, role string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserRole", ctx, actorID, userID, role)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserRole indicates an expected call of SetUserRole.
func (mr *MockAdminUserMockRecorder) SetUserRole(ctx, actorID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserRole", reflect.TypeOf((*MockAdminUser)(nil).SetUserRole), ctx, actorID, userID, role)
}

// MockVideo is a mock of Video interface.
type MockVideo struct {
	ctrl     *gomock.Controller
	recorder *MockVideoMockRecorder
	isgomock struct{}
}

// MockVideoMockRecorder is the mock recorder for MockVideo.
type MockVideoMockRecorder struct {
	mock *MockVideo
}

// NewMockVideo creates a new mock instance.
func NewMockVideo(ctrl *gomock.Controller) *MockVideo {
	mock := &MockVideo{ctrl: ctrl}
	mock.recorder = &MockVideoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideo) EXPECT() *MockVideoMockRecorder {
	return m.recorder
}

// AddUserYouTubeVideo mocks base method.
func (m *MockVideo) AddUserYouTubeVideo(ctx context.Context, userID, youtubeURLOrID string) (entity.Video, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserYouTubeVideo", ctx, userID, youtubeURLOrID)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddUserYouTubeVideo indicates an expected call of AddUserYouTubeVideo.
func (mr *MockVideoMockRecorder) AddUserYouTubeVideo(ctx, userID, youtubeURLOrID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserYouTubeVideo", reflect.TypeOf((*MockVideo)(nil).AddUserYouTubeVideo), ctx, userID, youtubeURLOrID)
}

// CreateVideo mocks base method.
func (m *MockVideo) CreateVideo(ctx context.Context, input entity.VideoInput) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideo", ctx, input)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVideo indicates an expected call of CreateVideo.
func (mr *MockVideoMockRecorder) CreateVideo(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideo", reflect.TypeOf((*MockVideo)(nil).CreateVideo), ctx, input)
}

// DeleteVideo mocks base method.
func (m *MockVideo) DeleteVideo(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVideo", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVideo indicates an expected call of DeleteVideo.
func (mr *MockVideoMockRecorder) DeleteVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideo", reflect.TypeOf((*MockVideo)(nil).DeleteVideo), ctx, id)
}

// GetVideo mocks base method.
func (m *MockVideo) GetVideo(ctx context.Context, id int64) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideo", ctx, id)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideo indicates an expected call of GetVideo.
func (mr *MockVideoMockRecorder) GetVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideo", reflect.TypeOf((*MockVideo)(nil).GetVideo), ctx, id)
}

// ListVideos mocks base method.
func (m *MockVideo) ListVideos(ctx context.Context, filter entity.VideoFilter) (entity.VideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideos", ctx, filter)
	ret0, _ := ret[0].(entity.VideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideos indicates an expected call of ListVideos.
func (mr *MockVideoMockRecorder) ListVideos(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideos", reflect.TypeOf((*MockVideo)(nil).ListVideos), ctx, filter)
}

// PreviewYouTubeVideo mocks base method.
func (m *MockVideo) PreviewYouTubeVideo(ctx context.Context, youtubeURLOrID string) (entity.YouTubeVideoPreview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreviewYouTubeVideo", ctx, youtubeURLOrID)
	ret0, _ := ret[0].(entity.YouTubeVideoPreview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreviewYouTubeVideo indicates an expected call of PreviewYouTubeVideo.
func (mr *MockVideoMockRecorder) PreviewYouTubeVideo(ctx, youtubeURLOrID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewYouTubeVideo", reflect.TypeOf((*MockVideo)(nil).PreviewYouTubeVideo), ctx, youtubeURLOrID)
}

// TransitionVideoStatus mocks base method.
func (m *MockVideo) TransitionVideoStatus(ctx context.Context, id int64, status string) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionVideoStatus", ctx, id, status)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionVideoStatus indicates an expected call of TransitionVideoStatus.
func (mr *MockVideoMockRecorder) TransitionVideoStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionVideoStatus", reflect.TypeOf((*MockVideo)(nil).TransitionVideoStatus), ctx, id, status)
}

// UpdateVideo mocks base method.
func (m *MockVideo) UpdateVideo(ctx context.Context, id int64, input entity.VideoInput) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideo", ctx, id, input)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVideo indicates an expected call of UpdateVideo.
func (mr *MockVideoMockRecorder) UpdateVideo(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideo", reflect.TypeOf((*MockVideo)(nil).UpdateVideo), ctx, id, input)
}

// MockCaption is a mock of Caption interface.
type MockCaption struct {
	ctrl     *gomock.Controller
	recorder *MockCaptionMockRecorder
	isgomock struct{}
}

// MockCaptionMockRecorder is the mock recorder for MockCaption.
type MockCaptionMockRecorder struct {
	mock *MockCaption
}

// NewMockCaption creates a new mock instance.
func NewMockCaption(ctrl *gomock.Controller) *MockCaption {
	mock := &MockCaption{ctrl: ctrl}
	mock.recorder = &MockCaptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaption) EXPECT() *MockCaptionMockRecorder {
	return m.recorder
}

// CreateCaption mocks base method.
func (m *MockCaption) CreateCaption(ctx context.Context, videoID int64, input entity.CaptionInput) (entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCaption", ctx, videoID, input)
	ret0, _ := ret[0].(entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCaption indicates an expected call of CreateCaption.
func (mr *MockCaptionMockRecorder) CreateCaption(ctx, videoID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCaption", reflect.TypeOf((*MockCaption)(nil).CreateCaption), ctx, videoID, input)
}

// DeleteCaption mocks base method.
func (m *MockCaption) DeleteCaption(ctx context.Context, videoID, captionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCaption", ctx, videoID, captionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCaption indicates an expected call of DeleteCaption.
func (mr *MockCaptionMockRecorder) DeleteCaption(ctx, videoID, captionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCaption", reflect.TypeOf((*MockCaption)(nil).DeleteCaption), ctx, videoID, captionID)
}

// GetOriginalCaptions mocks base method.
func (m *MockCaption) GetOriginalCaptions(ctx context.Context, videoID int64) (entity.VideoCaptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalCaptions", ctx, videoID)
	ret0, _ := ret[0].(entity.VideoCaptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginalCaptions indicates an expected call of GetOriginalCaptions.
func (mr *MockCaptionMockRecorder) GetOriginalCaptions(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalCaptions", reflect.TypeOf((*MockCaption)(nil).GetOriginalCaptions), ctx, videoID)
}

// GetTranslatedCaptions mocks base method.
func (m *MockCaption) GetTranslatedCaptions(ctx context.Context, userID string, videoID int64) (entity.VideoCaptions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTranslatedCaptions", ctx, userID, videoID)
	ret0, _ := ret[0].(entity.VideoCaptions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTranslatedCaptions indicates an expected call of GetTranslatedCaptions.
func (mr *MockCaptionMockRecorder) GetTranslatedCaptions(ctx, userID, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTranslatedCaptions", reflect.TypeOf((*MockCaption)(nil).GetTranslatedCaptions), ctx, userID, videoID)
}

// ImportFromYouTube mocks base method.
func (m *MockCaption) ImportFromYouTube(ctx context.Context, videoID int64, languageCode, mode string) (entity.YouTubeCaptionImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportFromYouTube", ctx, videoID, languageCode, mode)
	ret0, _ := ret[0].(entity.YouTubeCaptionImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportFromYouTube indicates an expected call of ImportFromYouTube.
func (mr *MockCaptionMockRecorder) ImportFromYouTube(ctx, videoID, languageCode, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportFromYouTube", reflect.TypeOf((*MockCaption)(nil).ImportFromYouTube), ctx, videoID, languageCode, mode)
}

// ImportSRT mocks base method.
func (m *MockCaption) ImportSRT(ctx context.Context, videoID int64, original []byte, translations []entity.SRTTranslationFile) ([]entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportSRT", ctx, videoID, original, translations)
	ret0, _ := ret[0].([]entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportSRT indicates an expected call of ImportSRT.
func (mr *MockCaptionMockRecorder) ImportSRT(ctx, videoID, original, translations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportSRT", reflect.TypeOf((*MockCaption)(nil).ImportSRT), ctx, videoID, original, translations)
}

// ListCaptions mocks base method.
func (m *MockCaption) ListCaptions(ctx context.Context, videoID int64, filter entity.CaptionFilter) (entity.CaptionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCaptions", ctx, videoID, filter)
	ret0, _ := ret[0].(entity.CaptionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCaptions indicates an expected call of ListCaptions.
func (mr *MockCaptionMockRecorder) ListCaptions(ctx, videoID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCaptions", reflect.TypeOf((*MockCaption)(nil).ListCaptions), ctx, videoID, filter)
}

// TranslateCaptions mocks base method.
func (m *MockCaption) TranslateCaptions(ctx context.Context, videoID int64, targetLanguageID int, mode string) (entity.CaptionTranslationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslateCaptions", ctx, videoID, targetLanguageID, mode)
	ret0, _ := ret[0].(entity.CaptionTranslationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslateCaptions indicates an expected call of TranslateCaptions.
func (mr *MockCaptionMockRecorder) TranslateCaptions(ctx, videoID, targetLanguageID, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateCaptions", reflect.TypeOf((*MockCaption)(nil).TranslateCaptions), ctx, videoID, targetLanguageID, mode)
}

// UpdateCaption mocks base method.
func (m *MockCaption) UpdateCaption(ctx context.Context, videoID, captionID int64, input entity.CaptionInput) (entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCaption", ctx, videoID, captionID, input)
	ret0, _ := ret[0].(entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCaption indicates an expected call of UpdateCaption.
func (mr *MockCaptionMockRecorder) UpdateCaption(ctx, videoID, captionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCaption", reflect.TypeOf((*MockCaption)(nil).UpdateCaption), ctx, videoID, captionID, input)
}

// MockVocabulary is a mock of Vocabulary interface.
type MockVocabulary struct {
	ctrl     *gomock.Controller
	recorder *MockVocabularyMockRecorder
	isgomock struct{}
}

// MockVocabularyMockRecorder is the mock recorder for MockVocabulary.
type MockVocabularyMockRecorder struct {
	mock *MockVocabulary
}

// NewMockVocabulary creates a new mock instance.
func NewMockVocabulary(ctrl *gomock.Controller) *MockVocabulary {
	mock := &MockVocabulary{ctrl: ctrl}
	mock.recorder = &MockVocabularyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVocabulary) EXPECT() *MockVocabularyMockRecorder {
	return m.recorder
}

// CreateSet mocks base method.
func (m *MockVocabulary) CreateSet(ctx context.Context, userID, title string) (entity.VocabularySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSet", ctx, userID, title)
	ret0, _ := ret[0].(entity.VocabularySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSet indicates an expected call of CreateSet.
func (mr *MockVocabularyMockRecorder) CreateSet(ctx, userID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSet", reflect.TypeOf((*MockVocabulary)(nil).CreateSet), ctx, userID, title)
}

// CreateUserVocabulary mocks base method.
func (m *MockVocabulary) CreateUserVocabulary(ctx context.Context, userID string, input entity.UserVocabularyInput) (entity.UserVocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserVocabulary", ctx, userID, input)
	ret0, _ := ret[0].(entity.UserVocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserVocabulary indicates an expected call of CreateUserVocabulary.
func (mr *MockVocabularyMockRecorder) CreateUserVocabulary(ctx, userID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserVocabulary", reflect.TypeOf((*MockVocabulary)(nil).CreateUserVocabulary), ctx, userID, input)
}

// DeleteSet mocks base method.
func (m *MockVocabulary) DeleteSet(ctx context.Context, userID string, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSet", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSet indicates an expected call of DeleteSet.
func (mr *MockVocabularyMockRecorder) DeleteSet(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSet", reflect.TypeOf((*MockVocabulary)(nil).DeleteSet), ctx, userID, id)
}

// DeleteUserVocabulary mocks base method.
func (m *MockVocabulary) DeleteUserVocabulary(ctx context.Context, userID string, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserVocabulary", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserVocabulary indicates an expected call of DeleteUserVocabulary.
func (mr *MockVocabularyMockRecorder) DeleteUserVocabulary(ctx, userID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserVocabulary", reflect.TypeOf((*MockVocabulary)(nil).DeleteUserVocabulary), ctx, userID, id)
}

// ListSets mocks base method.
func (m *MockVocabulary) ListSets(ctx context.Context, userID string) ([]entity.VocabularySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSets", ctx, userID)
	ret0, _ := ret[0].([]entity.VocabularySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSets indicates an expected call of ListSets.
func (mr *MockVocabularyMockRecorder) ListSets(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSets", reflect.TypeOf((*MockVocabulary)(nil).ListSets), ctx, userID)
}

// ListUserVocabularies mocks base method.
func (m *MockVocabulary) ListUserVocabularies(ctx context.Context, userID string, vocabSetID *int64) ([]entity.UserVocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserVocabularies", ctx, userID, vocabSetID)
	ret0, _ := ret[0].([]entity.UserVocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserVocabularies indicates an expected call of ListUserVocabularies.
func (mr *MockVocabularyMockRecorder) ListUserVocabularies(ctx, userID, vocabSetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserVocabularies", reflect.TypeOf((*MockVocabulary)(nil).ListUserVocabularies), ctx, userID, vocabSetID)
}

// TranslateWord mocks base method.
func (m *MockVocabulary) TranslateWord(ctx context.Context, userID, word string) (entity.VocabularyLookupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslateWord", ctx, userID, word)
	ret0, _ := ret[0].(entity.VocabularyLookupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TranslateWord indicates an expected call of TranslateWord.
func (mr *MockVocabularyMockRecorder) TranslateWord(ctx, userID, word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateWord", reflect.TypeOf((*MockVocabulary)(nil).TranslateWord), ctx, userID, word)
}

// UpdateSet mocks base method.
func (m *MockVocabulary) UpdateSet(ctx context.Context, userID string, id int64, title string) (entity.VocabularySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSet", ctx, userID, id, title)
	ret0, _ := ret[0].(entity.VocabularySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSet indicates an expected call of UpdateSet.
func (mr *MockVocabularyMockRecorder) UpdateSet(ctx, userID, id, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSet", reflect.TypeOf((*MockVocabulary)(nil).UpdateSet), ctx, userID, id, title)
}

// UpdateUserVocabulary mocks base method.
func (m *MockVocabulary) UpdateUserVocabulary(ctx context.Context, userID string, id int64, input entity.UserVocabularyUpdate) (entity.UserVocabulary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserVocabulary", ctx, userID, id, input)
	ret0, _ := ret[0].(entity.UserVocabulary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserVocabulary indicates an expected call of UpdateUserVocabulary.
func (mr *MockVocabularyMockRecorder) UpdateUserVocabulary(ctx, userID, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserVocabulary", reflect.TypeOf((*MockVocabulary)(nil).UpdateUserVocabulary), ctx, userID, id, input)
}
