// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	repo "github.com/evrone/go-clean-template/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslationRepo is a mock of TranslationRepo interface.
type MockTranslationRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationRepoMockRecorder
	isgomock struct{}
}

// MockTranslationRepoMockRecorder is the mock recorder for MockTranslationRepo.
type MockTranslationRepoMockRecorder struct {
	mock *MockTranslationRepo
}

// NewMockTranslationRepo creates a new mock instance.
func NewMockTranslationRepo(ctrl *gomock.Controller) *MockTranslationRepo {
	mock := &MockTranslationRepo{ctrl: ctrl}
	mock.recorder = &MockTranslationRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationRepo) EXPECT() *MockTranslationRepoMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockTranslationRepo) GetHistory(ctx context.Context, userID string) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockTranslationRepoMockRecorder) GetHistory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockTranslationRepo)(nil).GetHistory), ctx, userID)
}

// Store mocks base method.
func (m *MockTranslationRepo) Store(ctx context.Context, userID string, t entity.Translation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, userID, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockTranslationRepoMockRecorder) Store(ctx, userID, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockTranslationRepo)(nil).Store), ctx, userID, t)
}

// MockTranslationWebAPI is a mock of TranslationWebAPI interface.
type MockTranslationWebAPI struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationWebAPIMockRecorder
	isgomock struct{}
}

// MockTranslationWebAPIMockRecorder is the mock recorder for MockTranslationWebAPI.
type MockTranslationWebAPIMockRecorder struct {
	mock *MockTranslationWebAPI
}

// NewMockTranslationWebAPI creates a new mock instance.
func NewMockTranslationWebAPI(ctrl *gomock.Controller) *MockTranslationWebAPI {
	mock := &MockTranslationWebAPI{ctrl: ctrl}
	mock.recorder = &MockTranslationWebAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslationWebAPI) EXPECT() *MockTranslationWebAPIMockRecorder {
	return m.recorder
}

// Translate mocks base method.
func (m *MockTranslationWebAPI) Translate(ctx context.Context, t entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", ctx, t)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationWebAPIMockRecorder) Translate(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslationWebAPI)(nil).Translate), ctx, t)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockUserRepo) GetByEmail(ctx context.Context, email string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockUserRepoMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockUserRepo)(nil).GetByEmail), ctx, email)
}

// GetByFirebaseUID mocks base method.
func (m *MockUserRepo) GetByFirebaseUID(ctx context.Context, firebaseUID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFirebaseUID", ctx, firebaseUID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFirebaseUID indicates an expected call of GetByFirebaseUID.
func (mr *MockUserRepoMockRecorder) GetByFirebaseUID(ctx, firebaseUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFirebaseUID", reflect.TypeOf((*MockUserRepo)(nil).GetByFirebaseUID), ctx, firebaseUID)
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// Store mocks base method.
func (m *MockUserRepo) Store(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockUserRepoMockRecorder) Store(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockUserRepo)(nil).Store), ctx, user)
}

// MockContentRepo is a mock of ContentRepo interface.
type MockContentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockContentRepoMockRecorder
	isgomock struct{}
}

// MockContentRepoMockRecorder is the mock recorder for MockContentRepo.
type MockContentRepoMockRecorder struct {
	mock *MockContentRepo
}

// NewMockContentRepo creates a new mock instance.
func NewMockContentRepo(ctrl *gomock.Controller) *MockContentRepo {
	mock := &MockContentRepo{ctrl: ctrl}
	mock.recorder = &MockContentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentRepo) EXPECT() *MockContentRepoMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockContentRepo) CreateChannel(arg0 context.Context, arg1 *entity.Channel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockContentRepoMockRecorder) CreateChannel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockContentRepo)(nil).CreateChannel), arg0, arg1)
}

// CreateLevel mocks base method.
func (m *MockContentRepo) CreateLevel(arg0 context.Context, arg1 *entity.Level) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLevel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLevel indicates an expected call of CreateLevel.
func (mr *MockContentRepoMockRecorder) CreateLevel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLevel", reflect.TypeOf((*MockContentRepo)(nil).CreateLevel), arg0, arg1)
}

// CreateTopic mocks base method.
func (m *MockContentRepo) CreateTopic(arg0 context.Context, arg1 *entity.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockContentRepoMockRecorder) CreateTopic(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockContentRepo)(nil).CreateTopic), arg0, arg1)
}

// CreateVideo mocks base method.
func (m *MockContentRepo) CreateVideo(arg0 context.Context, arg1 *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVideo indicates an expected call of CreateVideo.
func (mr *MockContentRepoMockRecorder) CreateVideo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideo", reflect.TypeOf((*MockContentRepo)(nil).CreateVideo), arg0, arg1)
}

// DeleteChannel mocks base method.
func (m *MockContentRepo) DeleteChannel(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockContentRepoMockRecorder) DeleteChannel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockContentRepo)(nil).DeleteChannel), arg0, arg1)
}

// DeleteLevel mocks base method.
func (m *MockContentRepo) DeleteLevel(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLevel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLevel indicates an expected call of DeleteLevel.
func (mr *MockContentRepoMockRecorder) DeleteLevel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLevel", reflect.TypeOf((*MockContentRepo)(nil).DeleteLevel), arg0, arg1)
}

// DeleteTopic mocks base method.
func (m *MockContentRepo) DeleteTopic(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockContentRepoMockRecorder) DeleteTopic(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockContentRepo)(nil).DeleteTopic), arg0, arg1)
}

// DeleteVideo mocks base method.
func (m *MockContentRepo) DeleteVideo(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVideo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVideo indicates an expected call of DeleteVideo.
func (mr *MockContentRepoMockRecorder) DeleteVideo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideo", reflect.TypeOf((*MockContentRepo)(nil).DeleteVideo), arg0, arg1)
}

// GetChannel mocks base method.
func (m *MockContentRepo) GetChannel(arg0 context.Context, arg1 int64) (entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel", arg0, arg1)
	ret0, _ := ret[0].(entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockContentRepoMockRecorder) GetChannel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockContentRepo)(nil).GetChannel), arg0, arg1)
}

// GetLevel mocks base method.
func (m *MockContentRepo) GetLevel(arg0 context.Context, arg1 int64) (entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLevel", arg0, arg1)
	ret0, _ := ret[0].(entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLevel indicates an expected call of GetLevel.
func (mr *MockContentRepoMockRecorder) GetLevel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLevel", reflect.TypeOf((*MockContentRepo)(nil).GetLevel), arg0, arg1)
}

// GetTopic mocks base method.
func (m *MockContentRepo) GetTopic(arg0 context.Context, arg1 int64) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopic", arg0, arg1)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopic indicates an expected call of GetTopic.
func (mr *MockContentRepoMockRecorder) GetTopic(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopic", reflect.TypeOf((*MockContentRepo)(nil).GetTopic), arg0, arg1)
}

// GetVideo mocks base method.
func (m *MockContentRepo) GetVideo(arg0 context.Context, arg1 int64) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideo", arg0, arg1)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideo indicates an expected call of GetVideo.
func (mr *MockContentRepoMockRecorder) GetVideo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideo", reflect.TypeOf((*MockContentRepo)(nil).GetVideo), arg0, arg1)
}

// ListChannels mocks base method.
func (m *MockContentRepo) ListChannels(arg0 context.Context, arg1 repo.ContentFilter) ([]entity.Channel, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", arg0, arg1)
	ret0, _ := ret[0].([]entity.Channel)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockContentRepoMockRecorder) ListChannels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockContentRepo)(nil).ListChannels), arg0, arg1)
}

// ListLevels mocks base method.
func (m *MockContentRepo) ListLevels(arg0 context.Context, arg1 repo.ContentFilter) ([]entity.Level, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLevels", arg0, arg1)
	ret0, _ := ret[0].([]entity.Level)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLevels indicates an expected call of ListLevels.
func (mr *MockContentRepoMockRecorder) ListLevels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLevels", reflect.TypeOf((*MockContentRepo)(nil).ListLevels), arg0, arg1)
}

// ListTopics mocks base method.
func (m *MockContentRepo) ListTopics(arg0 context.Context, arg1 repo.ContentFilter) ([]entity.Topic, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", arg0, arg1)
	ret0, _ := ret[0].([]entity.Topic)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockContentRepoMockRecorder) ListTopics(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockContentRepo)(nil).ListTopics), arg0, arg1)
}

// ListVideos mocks base method.
func (m *MockContentRepo) ListVideos(arg0 context.Context, arg1 repo.ContentFilter) ([]entity.Video, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideos", arg0, arg1)
	ret0, _ := ret[0].([]entity.Video)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListVideos indicates an expected call of ListVideos.
func (mr *MockContentRepoMockRecorder) ListVideos(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideos", reflect.TypeOf((*MockContentRepo)(nil).ListVideos), arg0, arg1)
}

// UpdateChannel mocks base method.
func (m *MockContentRepo) UpdateChannel(arg0 context.Context, arg1 *entity.Channel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockContentRepoMockRecorder) UpdateChannel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockContentRepo)(nil).UpdateChannel), arg0, arg1)
}

// UpdateLevel mocks base method.
func (m *MockContentRepo) UpdateLevel(arg0 context.Context, arg1 *entity.Level) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLevel", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLevel indicates an expected call of UpdateLevel.
func (mr *MockContentRepoMockRecorder) UpdateLevel(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLevel", reflect.TypeOf((*MockContentRepo)(nil).UpdateLevel), arg0, arg1)
}

// UpdateTopic mocks base method.
func (m *MockContentRepo) UpdateTopic(arg0 context.Context, arg1 *entity.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTopic", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTopic indicates an expected call of UpdateTopic.
func (mr *MockContentRepoMockRecorder) UpdateTopic(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTopic", reflect.TypeOf((*MockContentRepo)(nil).UpdateTopic), arg0, arg1)
}

// UpdateVideo mocks base method.
func (m *MockContentRepo) UpdateVideo(arg0 context.Context, arg1 *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideo", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVideo indicates an expected call of UpdateVideo.
func (mr *MockContentRepoMockRecorder) UpdateVideo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideo", reflect.TypeOf((*MockContentRepo)(nil).UpdateVideo), arg0, arg1)
}
