// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=./mocks_usecase_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/evrone/go-clean-template/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
	isgomock struct{}
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockUser) Authenticate(ctx context.Context, identity entity.AuthIdentity) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, identity)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockUserMockRecorder) Authenticate(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockUser)(nil).Authenticate), ctx, identity)
}

// GetUser mocks base method.
func (m *MockUser) GetUser(ctx context.Context, userID string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUser)(nil).GetUser), ctx, userID)
}

// Login mocks base method.
func (m *MockUser) Login(ctx context.Context, email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUser)(nil).Login), ctx, email, password)
}

// Register mocks base method.
func (m *MockUser) Register(ctx context.Context, username, email, password string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockUserMockRecorder) Register(ctx, username, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUser)(nil).Register), ctx, username, email, password)
}

// MockLanguage is a mock of Language interface.
type MockLanguage struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageMockRecorder
	isgomock struct{}
}

// MockLanguageMockRecorder is the mock recorder for MockLanguage.
type MockLanguageMockRecorder struct {
	mock *MockLanguage
}

// NewMockLanguage creates a new mock instance.
func NewMockLanguage(ctrl *gomock.Controller) *MockLanguage {
	mock := &MockLanguage{ctrl: ctrl}
	mock.recorder = &MockLanguageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguage) EXPECT() *MockLanguageMockRecorder {
	return m.recorder
}

// CreateLanguage mocks base method.
func (m *MockLanguage) CreateLanguage(ctx context.Context, code, name string) (entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLanguage", ctx, code, name)
	ret0, _ := ret[0].(entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLanguage indicates an expected call of CreateLanguage.
func (mr *MockLanguageMockRecorder) CreateLanguage(ctx, code, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLanguage", reflect.TypeOf((*MockLanguage)(nil).CreateLanguage), ctx, code, name)
}

// ListLanguages mocks base method.
func (m *MockLanguage) ListLanguages(ctx context.Context) ([]entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLanguages", ctx)
	ret0, _ := ret[0].([]entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLanguages indicates an expected call of ListLanguages.
func (mr *MockLanguageMockRecorder) ListLanguages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLanguages", reflect.TypeOf((*MockLanguage)(nil).ListLanguages), ctx)
}

// UpdateLanguage mocks base method.
func (m *MockLanguage) UpdateLanguage(ctx context.Context, id int, name string, isActive bool) (entity.Language, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLanguage", ctx, id, name, isActive)
	ret0, _ := ret[0].(entity.Language)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLanguage indicates an expected call of UpdateLanguage.
func (mr *MockLanguageMockRecorder) UpdateLanguage(ctx, id, name, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLanguage", reflect.TypeOf((*MockLanguage)(nil).UpdateLanguage), ctx, id, name, isActive)
}

// MockLevel is a mock of Level interface.
type MockLevel struct {
	ctrl     *gomock.Controller
	recorder *MockLevelMockRecorder
	isgomock struct{}
}

// MockLevelMockRecorder is the mock recorder for MockLevel.
type MockLevelMockRecorder struct {
	mock *MockLevel
}

// NewMockLevel creates a new mock instance.
func NewMockLevel(ctrl *gomock.Controller) *MockLevel {
	mock := &MockLevel{ctrl: ctrl}
	mock.recorder = &MockLevelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLevel) EXPECT() *MockLevelMockRecorder {
	return m.recorder
}

// CreateLevel mocks base method.
func (m *MockLevel) CreateLevel(ctx context.Context, level entity.Level) (entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLevel", ctx, level)
	ret0, _ := ret[0].(entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLevel indicates an expected call of CreateLevel.
func (mr *MockLevelMockRecorder) CreateLevel(ctx, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLevel", reflect.TypeOf((*MockLevel)(nil).CreateLevel), ctx, level)
}

// DeleteLevel mocks base method.
func (m *MockLevel) DeleteLevel(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLevel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLevel indicates an expected call of DeleteLevel.
func (mr *MockLevelMockRecorder) DeleteLevel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLevel", reflect.TypeOf((*MockLevel)(nil).DeleteLevel), ctx, id)
}

// ListLevels mocks base method.
func (m *MockLevel) ListLevels(ctx context.Context, languageID *int) ([]entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLevels", ctx, languageID)
	ret0, _ := ret[0].([]entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLevels indicates an expected call of ListLevels.
func (mr *MockLevelMockRecorder) ListLevels(ctx, languageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLevels", reflect.TypeOf((*MockLevel)(nil).ListLevels), ctx, languageID)
}

// UpdateLevel mocks base method.
func (m *MockLevel) UpdateLevel(ctx context.Context, id int, level entity.Level) (entity.Level, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLevel", ctx, id, level)
	ret0, _ := ret[0].(entity.Level)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLevel indicates an expected call of UpdateLevel.
func (mr *MockLevelMockRecorder) UpdateLevel(ctx, id, level any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLevel", reflect.TypeOf((*MockLevel)(nil).UpdateLevel), ctx, id, level)
}

// MockTopic is a mock of Topic interface.
type MockTopic struct {
	ctrl     *gomock.Controller
	recorder *MockTopicMockRecorder
	isgomock struct{}
}

// MockTopicMockRecorder is the mock recorder for MockTopic.
type MockTopicMockRecorder struct {
	mock *MockTopic
}

// NewMockTopic creates a new mock instance.
func NewMockTopic(ctrl *gomock.Controller) *MockTopic {
	mock := &MockTopic{ctrl: ctrl}
	mock.recorder = &MockTopicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopic) EXPECT() *MockTopicMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method.
func (m *MockTopic) CreateTopic(ctx context.Context, topic entity.Topic) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, topic)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockTopicMockRecorder) CreateTopic(ctx, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockTopic)(nil).CreateTopic), ctx, topic)
}

// DeleteTopic mocks base method.
func (m *MockTopic) DeleteTopic(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic.
func (mr *MockTopicMockRecorder) DeleteTopic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockTopic)(nil).DeleteTopic), ctx, id)
}

// ListTopics mocks base method.
func (m *MockTopic) ListTopics(ctx context.Context) ([]entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx)
	ret0, _ := ret[0].([]entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockTopicMockRecorder) ListTopics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockTopic)(nil).ListTopics), ctx)
}

// SetTopicActive mocks base method.
func (m *MockTopic) SetTopicActive(ctx context.Context, id int, isActive bool) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTopicActive", ctx, id, isActive)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTopicActive indicates an expected call of SetTopicActive.
func (mr *MockTopicMockRecorder) SetTopicActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopicActive", reflect.TypeOf((*MockTopic)(nil).SetTopicActive), ctx, id, isActive)
}

// UpdateTopic mocks base method.
func (m *MockTopic) UpdateTopic(ctx context.Context, id int, topic entity.Topic) (entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTopic", ctx, id, topic)
	ret0, _ := ret[0].(entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTopic indicates an expected call of UpdateTopic.
func (mr *MockTopicMockRecorder) UpdateTopic(ctx, id, topic any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTopic", reflect.TypeOf((*MockTopic)(nil).UpdateTopic), ctx, id, topic)
}

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockChannel) CreateChannel(ctx context.Context, channel entity.Channel) (entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", ctx, channel)
	ret0, _ := ret[0].(entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockChannelMockRecorder) CreateChannel(ctx, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockChannel)(nil).CreateChannel), ctx, channel)
}

// DeleteChannel mocks base method.
func (m *MockChannel) DeleteChannel(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChannel", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChannel indicates an expected call of DeleteChannel.
func (mr *MockChannelMockRecorder) DeleteChannel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChannel", reflect.TypeOf((*MockChannel)(nil).DeleteChannel), ctx, id)
}

// ListChannels mocks base method.
func (m *MockChannel) ListChannels(ctx context.Context) ([]entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChannels", ctx)
	ret0, _ := ret[0].([]entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChannels indicates an expected call of ListChannels.
func (mr *MockChannelMockRecorder) ListChannels(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChannels", reflect.TypeOf((*MockChannel)(nil).ListChannels), ctx)
}

// UpdateChannel mocks base method.
func (m *MockChannel) UpdateChannel(ctx context.Context, id int, channel entity.Channel) (entity.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", ctx, id, channel)
	ret0, _ := ret[0].(entity.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockChannelMockRecorder) UpdateChannel(ctx, id, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockChannel)(nil).UpdateChannel), ctx, id, channel)
}

// MockAdminUser is a mock of AdminUser interface.
type MockAdminUser struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserMockRecorder
	isgomock struct{}
}

// MockAdminUserMockRecorder is the mock recorder for MockAdminUser.
type MockAdminUserMockRecorder struct {
	mock *MockAdminUser
}

// NewMockAdminUser creates a new mock instance.
func NewMockAdminUser(ctrl *gomock.Controller) *MockAdminUser {
	mock := &MockAdminUser{ctrl: ctrl}
	mock.recorder = &MockAdminUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUser) EXPECT() *MockAdminUserMockRecorder {
	return m.recorder
}

// ListUsers mocks base method.
func (m *MockAdminUser) ListUsers(ctx context.Context, filter entity.UserFilter) (entity.UserList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, filter)
	ret0, _ := ret[0].(entity.UserList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminUserMockRecorder) ListUsers(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminUser)(nil).ListUsers), ctx, filter)
}

// SetUserActive mocks base method.
func (m *MockAdminUser) SetUserActive(ctx context.Context, actorID, userID string, isActive bool) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActive", ctx, actorID, userID, isActive)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActive indicates an expected call of SetUserActive.
func (mr *MockAdminUserMockRecorder) SetUserActive(ctx, actorID, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActive", reflect.TypeOf((*MockAdminUser)(nil).SetUserActive), ctx, actorID, userID, isActive)
}

// SetUserRole mocks base method.
func (m *MockAdminUser) SetUserRole(ctx context.Context, actorID, userID, role string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserRole", ctx, actorID, userID, role)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserRole indicates an expected call of SetUserRole.
func (mr *MockAdminUserMockRecorder) SetUserRole(ctx, actorID, userID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserRole", reflect.TypeOf((*MockAdminUser)(nil).SetUserRole), ctx, actorID, userID, role)
}

// MockVideo is a mock of Video interface.
type MockVideo struct {
	ctrl     *gomock.Controller
	recorder *MockVideoMockRecorder
	isgomock struct{}
}

// MockVideoMockRecorder is the mock recorder for MockVideo.
type MockVideoMockRecorder struct {
	mock *MockVideo
}

// NewMockVideo creates a new mock instance.
func NewMockVideo(ctrl *gomock.Controller) *MockVideo {
	mock := &MockVideo{ctrl: ctrl}
	mock.recorder = &MockVideoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideo) EXPECT() *MockVideoMockRecorder {
	return m.recorder
}

// CreateVideo mocks base method.
func (m *MockVideo) CreateVideo(ctx context.Context, input entity.VideoInput) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVideo", ctx, input)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVideo indicates an expected call of CreateVideo.
func (mr *MockVideoMockRecorder) CreateVideo(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVideo", reflect.TypeOf((*MockVideo)(nil).CreateVideo), ctx, input)
}

// DeleteVideo mocks base method.
func (m *MockVideo) DeleteVideo(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVideo", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVideo indicates an expected call of DeleteVideo.
func (mr *MockVideoMockRecorder) DeleteVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVideo", reflect.TypeOf((*MockVideo)(nil).DeleteVideo), ctx, id)
}

// GetVideo mocks base method.
func (m *MockVideo) GetVideo(ctx context.Context, id int64) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideo", ctx, id)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideo indicates an expected call of GetVideo.
func (mr *MockVideoMockRecorder) GetVideo(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideo", reflect.TypeOf((*MockVideo)(nil).GetVideo), ctx, id)
}

// ListVideos mocks base method.
func (m *MockVideo) ListVideos(ctx context.Context, filter entity.VideoFilter) (entity.VideoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVideos", ctx, filter)
	ret0, _ := ret[0].(entity.VideoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVideos indicates an expected call of ListVideos.
func (mr *MockVideoMockRecorder) ListVideos(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVideos", reflect.TypeOf((*MockVideo)(nil).ListVideos), ctx, filter)
}

// TransitionVideoStatus mocks base method.
func (m *MockVideo) TransitionVideoStatus(ctx context.Context, id int64, status string) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionVideoStatus", ctx, id, status)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransitionVideoStatus indicates an expected call of TransitionVideoStatus.
func (mr *MockVideoMockRecorder) TransitionVideoStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionVideoStatus", reflect.TypeOf((*MockVideo)(nil).TransitionVideoStatus), ctx, id, status)
}

// UpdateVideo mocks base method.
func (m *MockVideo) UpdateVideo(ctx context.Context, id int64, input entity.VideoInput) (entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVideo", ctx, id, input)
	ret0, _ := ret[0].(entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateVideo indicates an expected call of UpdateVideo.
func (mr *MockVideoMockRecorder) UpdateVideo(ctx, id, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVideo", reflect.TypeOf((*MockVideo)(nil).UpdateVideo), ctx, id, input)
}

// MockCaption is a mock of Caption interface.
type MockCaption struct {
	ctrl     *gomock.Controller
	recorder *MockCaptionMockRecorder
	isgomock struct{}
}

// MockCaptionMockRecorder is the mock recorder for MockCaption.
type MockCaptionMockRecorder struct {
	mock *MockCaption
}

// NewMockCaption creates a new mock instance.
func NewMockCaption(ctrl *gomock.Controller) *MockCaption {
	mock := &MockCaption{ctrl: ctrl}
	mock.recorder = &MockCaptionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCaption) EXPECT() *MockCaptionMockRecorder {
	return m.recorder
}

// CreateCaption mocks base method.
func (m *MockCaption) CreateCaption(ctx context.Context, videoID int64, input entity.CaptionInput) (entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCaption", ctx, videoID, input)
	ret0, _ := ret[0].(entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCaption indicates an expected call of CreateCaption.
func (mr *MockCaptionMockRecorder) CreateCaption(ctx, videoID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCaption", reflect.TypeOf((*MockCaption)(nil).CreateCaption), ctx, videoID, input)
}

// DeleteCaption mocks base method.
func (m *MockCaption) DeleteCaption(ctx context.Context, videoID, captionID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCaption", ctx, videoID, captionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCaption indicates an expected call of DeleteCaption.
func (mr *MockCaptionMockRecorder) DeleteCaption(ctx, videoID, captionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCaption", reflect.TypeOf((*MockCaption)(nil).DeleteCaption), ctx, videoID, captionID)
}

// ImportFromYouTube mocks base method.
func (m *MockCaption) ImportFromYouTube(ctx context.Context, videoID int64, languageCode, mode string) (entity.YouTubeCaptionImportResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportFromYouTube", ctx, videoID, languageCode, mode)
	ret0, _ := ret[0].(entity.YouTubeCaptionImportResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportFromYouTube indicates an expected call of ImportFromYouTube.
func (mr *MockCaptionMockRecorder) ImportFromYouTube(ctx, videoID, languageCode, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportFromYouTube", reflect.TypeOf((*MockCaption)(nil).ImportFromYouTube), ctx, videoID, languageCode, mode)
}

// ImportSRT mocks base method.
func (m *MockCaption) ImportSRT(ctx context.Context, videoID int64, original []byte, translations []entity.SRTTranslationFile) ([]entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImportSRT", ctx, videoID, original, translations)
	ret0, _ := ret[0].([]entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImportSRT indicates an expected call of ImportSRT.
func (mr *MockCaptionMockRecorder) ImportSRT(ctx, videoID, original, translations any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImportSRT", reflect.TypeOf((*MockCaption)(nil).ImportSRT), ctx, videoID, original, translations)
}

// ListCaptions mocks base method.
func (m *MockCaption) ListCaptions(ctx context.Context, videoID int64, filter entity.CaptionFilter) (entity.CaptionList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCaptions", ctx, videoID, filter)
	ret0, _ := ret[0].(entity.CaptionList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCaptions indicates an expected call of ListCaptions.
func (mr *MockCaptionMockRecorder) ListCaptions(ctx, videoID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCaptions", reflect.TypeOf((*MockCaption)(nil).ListCaptions), ctx, videoID, filter)
}

// ListYouTubeSubtitleTracks mocks base method.
func (m *MockCaption) ListYouTubeSubtitleTracks(ctx context.Context, videoID int64) (entity.YouTubeSubtitleTracks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListYouTubeSubtitleTracks", ctx, videoID)
	ret0, _ := ret[0].(entity.YouTubeSubtitleTracks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListYouTubeSubtitleTracks indicates an expected call of ListYouTubeSubtitleTracks.
func (mr *MockCaptionMockRecorder) ListYouTubeSubtitleTracks(ctx, videoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListYouTubeSubtitleTracks", reflect.TypeOf((*MockCaption)(nil).ListYouTubeSubtitleTracks), ctx, videoID)
}

// UpdateCaption mocks base method.
func (m *MockCaption) UpdateCaption(ctx context.Context, videoID, captionID int64, input entity.CaptionInput) (entity.Caption, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCaption", ctx, videoID, captionID, input)
	ret0, _ := ret[0].(entity.Caption)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCaption indicates an expected call of UpdateCaption.
func (mr *MockCaptionMockRecorder) UpdateCaption(ctx, videoID, captionID, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCaption", reflect.TypeOf((*MockCaption)(nil).UpdateCaption), ctx, videoID, captionID, input)
}
